/*
 * Decompiled with CFR 0.152.
 */
import main.GameMidlet;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public final class df {
    public static int a;
    public static String b;
    public static String c;
    public static String d;
    public static String e;
    public static String f;
    public static String g;
    public static String h;
    public static String i;
    public static String j;
    public static String k;
    public static String l;
    public static String m;
    public static String n;
    public static String o;
    public static String p;
    public static String q;
    public static String r;
    public static String s;
    public static String t;
    public static String u;
    public static String v;
    public static String w;
    public static String[] x;
    public static String y;
    public static String z;
    public static String A;
    public static String B;
    public static String C;
    public static String D;
    public static String E;
    public static String[] F;
    public static String G;
    public static String H;
    public static String I;
    public static String J;
    public static String K;
    public static String L;
    public static String M;
    public static String N;
    public static String O;
    public static String P;
    public static String Q;
    public static String R;
    public static String S;
    public static String T;
    public static String U;
    public static String V;
    public static String W;
    public static String X;
    public static String Y;
    public static String Z;
    public static String aa;
    public static String ab;
    public static String ac;
    public static String ad;
    public static String ae;
    public static String af;
    public static String ag;
    public static String ah;
    public static String ai;
    public static String aj;
    public static String ak;
    public static String al;
    public static String am;
    public static String an;
    public static String ao;
    public static String ap;
    public static String aq;
    public static String ar;
    public static String as;
    public static String at;
    public static String au;
    public static String av;
    public static String aw;
    public static String ax;
    public static String ay;
    public static String az;
    public static String aA;
    public static String aB;
    public static String aC;
    public static String aD;
    public static String aE;
    public static String aF;
    public static String aG;
    public static String aH;
    public static String aI;
    public static String aJ;
    public static String aK;
    public static String aL;
    public static String aM;
    public static String aN;
    public static String aO;
    public static String aP;
    public static String aQ;
    public static String aR;
    public static String[] aS;
    public static String aT;
    public static String aU;
    public static String aV;
    public static String[] aW;
    public static String aX;
    public static String aY;
    public static String aZ;
    public static String ba;
    public static String bb;
    public static String bc;
    public static String bd;
    public static String be;
    public static String bf;
    public static String bg;
    public static String bh;
    public static String bi;
    public static String bj;
    public static String bk;
    public static String bl;
    public static String bm;
    public static String bn;
    public static String bo;
    public static String bp;
    public static String bq;
    public static String br;
    public static String bs;
    public static String bt;
    public static String bu;
    public static String bv;
    public static String bw;
    public static String bx;
    public static String by;
    public static String bz;
    public static String bA;
    public static String bB;
    public static String bC;
    public static String bD;
    public static String bE;
    public static String bF;
    public static String bG;
    public static String bH;
    public static String bI;
    public static String bJ;
    public static String bK;
    public static String bL;
    public static String bM;
    public static String bN;
    public static String bO;
    public static String bP;
    public static String[] bQ;
    public static String bR;
    public static String bS;
    public static String bT;
    public static String bU;
    public static String bV;
    public static String bW;
    public static String bX;
    public static String bY;
    public static String bZ;
    public static String ca;
    public static String cb;
    public static String cc;
    public static String[] cd;
    public static String[] ce;
    public static String[][] cf;
    public static String[] cg;
    public static String[] ch;
    public static String[] ci;
    public static String[] cj;
    public static String[] ck;
    public static String[] cl;
    public static String[] cm;
    public static String[] cn;
    public static String[] co;
    public static String[] cp;
    public static String[] cq;
    public static String[] cr;
    public static String[] cs;
    public static String[] ct;
    public static String[] cu;
    public static String[] cv;
    public static String[] cw;
    public static String[] cx;
    public static String[] cy;
    public static String[] cz;
    public static String[] cA;
    public static String[] cB;
    public static String[] cC;
    public static String[] cD;
    public static String[] cE;
    public static String[] cF;
    public static String[] cG;
    public static String[] cH;
    public static String[] cI;
    public static String[] cJ;
    public static String[] cK;
    public static String[] cL;
    public static String[] cM;
    public static String[] cN;
    public static String[] cO;
    public static String[] cP;
    public static String[] cQ;
    public static String cR;
    public static String cS;
    public static String cT;
    public static String cU;
    public static String cV;
    public static String cW;
    public static String cX;
    public static String cY;
    public static String cZ;
    public static String da;
    public static String db;
    public static String dc;
    public static String dd;
    public static String de;
    public static String df;
    public static String dg;
    public static String dh;
    public static String di;
    public static String dj;
    public static String dk;
    public static String dl;
    public static String dm;
    public static String dn;
    public static String do;
    public static String dp;
    public static String dq;
    public static String dr;
    public static String ds;
    public static String dt;
    public static String du;
    public static String dv;
    public static String[] dw;
    public static String dx;
    public static String dy;
    public static String dz;
    public static String dA;
    public static String dB;
    public static String dC;
    public static String dD;
    public static String dE;
    public static String dF;
    public static String[] dG;
    public static String dH;
    public static String dI;
    public static String dJ;
    public static String dK;
    public static String dL;
    public static String dM;
    public static String[] dN;
    public static String[] dO;
    public static String[] dP;
    public static String dQ;
    public static String[] dR;
    public static String[] dS;
    public static String[] dT;
    public static String[] dU;
    public static String[] dV;
    public static String dW;
    public static String dX;
    public static String dY;
    public static String dZ;
    public static String[] ea;
    public static String eb;
    public static String ec;
    public static String ed;
    public static String ee;
    public static String ef;
    public static String eg;
    public static String eh;
    public static String ei;
    public static String ej;
    public static String ek;
    public static String el;
    public static String em;
    public static String en;
    public static String eo;
    public static String ep;
    public static String eq;
    public static String er;
    public static String es;
    public static String et;
    public static String eu;
    public static String ev;
    public static String ew;
    public static String ex;
    public static String ey;
    public static String ez;
    public static String eA;
    public static String eB;
    public static String eC;
    public static String eD;
    public static String eE;
    public static String eF;
    public static String eG;
    public static String eH;
    public static String eI;
    public static String[][] eJ;
    public static String[] eK;
    public static String[] eL;
    public static String eM;
    public static String eN;
    public static String eO;
    public static String eP;
    public static String eQ;
    public static String eR;
    public static String[] eS;
    public static String[] eT;
    public static String eU;
    public static String eV;
    public static String eW;
    public static String eX;
    public static String eY;
    public static String eZ;
    public static String fa;
    public static String fb;
    public static String fc;
    public static String fd;
    public static String fe;
    public static String ff;
    public static String fg;
    public static String fh;
    public static String fi;
    public static String fj;
    public static String fk;
    public static String fl;
    public static String fm;
    public static String fn;
    public static String fo;
    public static String fp;
    public static String fq;
    public static String fr;
    public static String fs;
    public static String ft;
    public static String fu;
    public static String fv;
    public static String fw;
    public static String fx;
    public static String fy;
    public static String fz;
    public static String fA;
    public static String[] fB;
    public static String fC;
    public static String fD;
    public static String fE;
    public static String fF;
    public static String fG;
    public static String[] fH;
    public static String[] fI;
    public static String[] fJ;
    public static String fK;
    public static String fL;
    public static String[][] fM;
    public static String[] fN;
    public static String[] fO;
    public static String[] fP;
    public static String[] fQ;
    public static String fR;
    public static String fS;
    public static String fT;
    public static String fU;
    public static String fV;
    public static String fW;
    public static String fX;
    public static String fY;
    public static String fZ;
    public static String ga;
    public static String[] gb;
    public static String gc;
    public static String[] gd;
    public static String[] ge;
    public static String gf;
    public static String gg;
    public static String gh;
    public static String gi;
    public static String gj;
    public static String gk;
    public static String gl;
    public static String gm;
    public static String gn;
    public static String go;
    public static String gp;
    public static String[] gq;
    public static String[] gr;
    public static String[] gs;
    public static String[] gt;
    public static String[] gu;
    public static String[] gv;
    public static String gw;
    public static String[] gx;
    public static String gy;
    public static String gz;
    public static String gA;
    public static String gB;
    public static String gC;
    public static String gD;
    public static String[] gE;
    public static String[] gF;
    public static String[] gG;
    public static String gH;
    public static String[] gI;
    public static String[] gJ;
    public static String[] gK;
    public static String[] gL;
    public static String gM;
    public static String gN;
    public static String gO;
    public static String gP;
    public static String gQ;
    public static String gR;
    public static String gS;
    public static String gT;
    public static String gU;
    public static String gV;
    public static String gW;
    public static String gX;
    public static String gY;
    public static String gZ;
    public static String ha;
    public static String hb;
    public static String hc;
    public static String hd;
    public static String he;
    public static String hf;
    public static String hg;
    public static String hh;
    public static String hi;
    public static String hj;
    public static String hk;
    public static String hl;
    public static String hm;
    public static String hn;
    public static String ho;
    public static String hp;
    public static String hq;
    public static String hr;
    public static String[] hs;
    public static String ht;
    public static String hu;
    public static String hv;
    public static String hw;
    public static String hx;
    public static String hy;
    public static String hz;
    public static String hA;
    public static String hB;
    public static String hC;
    public static String hD;
    public static String hE;
    public static String hF;
    public static String hG;
    public static String hH;
    public static String hI;
    public static String hJ;
    public static String hK;
    public static String hL;
    public static String hM;
    public static String[] hN;
    public static String hO;
    public static String hP;
    public static String hQ;
    public static String hR;
    public static String hS;
    public static String hT;
    public static String hU;
    public static String hV;
    public static String hW;
    public static String hX;
    public static String[][] hY;
    public static String[] hZ;
    public static String ia;
    public static String ib;
    public static String ic;
    public static String id;
    public static String[] ie;
    public static String if;
    public static String ig;
    public static String ih;
    public static String[] ii;
    public static String ij;
    public static String ik;
    public static String il;
    public static String im;
    public static String in;
    public static String io;
    public static String ip;
    public static String iq;
    public static String ir;
    public static String is;
    public static String it;
    public static String iu;
    public static String iv;
    public static String iw;
    public static String ix;
    public static String iy;
    public static String[] iz;
    public static String iA;
    public static String iB;
    public static String iC;
    public static String iD;
    public static String iE;
    public static String iF;
    public static String iG;
    public static String iH;
    public static String iI;
    public static String iJ;
    public static String iK;

    static {
        String[] stringArray = new String[]{"goldpack30", "goldpack70", "goldpack180", "goldpack380", "goldpack1000"};
    }

    public static void a(int n2) {
        a = n2;
        l.a(a);
        if (n2 == 0) {
            iI = "T.B\u1ecb 1";
            iJ = "T.B\u1ecb 2";
            GameMidlet.i = false;
            iK = "C\u1eadp nh\u1eadt m\u00e1y ch\u1ee7";
            c = "Vi\u00ean ng\u1ecdc n\u00e0y kh\u00f4ng th\u1ec3 g\u1ecdt.";
            b = "Vi\u00ean ng\u1ecdc \u0111\u00e3 \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 t\u1ed1i \u0111a.";
            d = "\u0110\u0103ng k\u00fd m\u1ed9t t\u00e0i kho\u1ea3n s\u1ebd gi\u00fap nh\u00e2n v\u1eadt \u0111ang ch\u01a1i c\u1ee7a b\u1ea1n c\u00f2n m\u00e3i. B\u1ea1n c\u00f3 mu\u1ed1n \u0111\u0103ng k\u00fd kh\u00f4ng?";
            e = "Nhi\u1ec7m v\u1ee5 b\u00ed \u1ea9n";
            f = "- N\u00e2ng hi\u1ebfu chi\u1ebfn l\u00ean 1.";
            g = "- Ho\u00e0n th\u00e0nh hang \u0111\u1ed9ng 1 l\u1ea7n.";
            h = "- Ho\u00e0n th\u00e0nh t\u00e0 th\u00fa 1 l\u1ea7n.";
            i = "- Ho\u00e0n th\u00e0nh 1 l\u1ea7n n\u00e2ng c\u1ea5p.";
            j = "- Ho\u00e0n th\u00e0nh 10 nhi\u1ec7m v\u1ee5 h\u00e0ng ng\u00e0y.";
            k = "- L\u1ea5y 1000 \u0111i\u1ec3m chi\u1ebfn tr\u01b0\u1eddng.";
            l = "- Ho\u00e0n th\u00e0nh 1 l\u1ea7n th\u1ea5t th\u00fa \u1ea3i.";
            m = "- Ho\u00e0n th\u00e0nh 3 l\u1ea7n quay s\u1ed1.";
            iH = "Ch\u01a1i qu\u00e1 180 ph\u00fat m\u1ed7i ng\u00e0y s\u1ebd h\u1ea1i s\u1ee9c kh\u1ecfe";
            p = "T\u1ec9 l\u1ec7 th\u1eafng";
            q = "B\u1ea1n \u0111\u00e3 tham gia: ";
            r = "S\u1ed1 ng\u01b0\u1eddi tham gia: ";
            s = "V\u00f2ng xoay may m\u1eafn";
            t = "Tham gia";
            iG = "Ti\u1ebfp t\u1ee5c";
            iB = "T\u00e0i kho\u1ea3n c\u1ee7a b\u1ea1n ch\u01b0a \u0111\u01b0\u1ee3c x\u00e1c th\u1ef1c. N\u1ebfu b\u1ea1n x\u00f3a tr\u00f2 ch\u01a1i, \u0111\u1ed5i khu v\u1ef1c, ho\u1eb7c \u0111\u0103ng nh\u1eadp t\u00e0i kho\u1ea3n kh\u00e1c, nh\u00e2n v\u1eadt \u0111ang ch\u01a1i c\u1ee7a b\u1ea1n s\u1ebd m\u1ea5t v\u0129nh vi\u1ec5n.";
            iC = "Ch\u01a1i m\u1edbi";
            iD = "Ch\u01a1i ti\u1ebfp";
            iE = "\u0110\u1ed5i t\u00e0i kho\u1ea3n";
            iF = "M\u00e1y Ch\u1ee7: ";
            u = "h\u1ea1ng";
            v = "Th\u00e1ch \u0110\u1ea5u";
            w = "Th\u00f4ng tin";
            x = new String[]{"B\u1ea1n c\u00f3 th\u1ec3 nh\u1ea5n gi\u1eef n\u00fat chuy\u1ec3n m\u1ee5c ti\u00eau \u0111\u1ec3 hi\u1ec3n th\u1ecb danh s\u00e1ch ng\u01b0\u1eddi ch\u01a1i kh\u00e1c trong map", "\u0110\u1ed1i v\u1edbi m\u00e1y c\u00f3 b\u00e0n ph\u00edm, b\u1ea1n c\u00f3 th\u1ec3 g\u00e1n ph\u00edm t\u1eaft cho c\u00e1c ph\u00edm 7,8,9 ho\u1eb7c Q,W,E \u0111\u1ec3 s\u1eed d\u1ee5ng k\u1ef9 n\u0103ng", "C\u1eebu s\u00e1t s\u1ebd l\u00e0m t\u0103ng 2 \u0111i\u1ec3m hi\u1ebfu chi\u1ebfn. \u0110\u1ed3 s\u00e1t s\u1ebd l\u00e0m t\u0103ng 1 \u0111i\u1ec3m hi\u1ebfu chi\u1ebfn", "\u0110\u1ed1i v\u1edbi Ki\u1ebfm, Kunai, \u0110ao: N\u00ean t\u0103ng S\u1ee9c M\u1ea1nh, Th\u1ec3 L\u1ef1c, Th\u00e2n ph\u00e1p", "\u0110\u1ed1i v\u1edbi Cung, Phi Ti\u00eau, Qu\u1ea1t: N\u00ean t\u0103ng Chakra, Th\u1ec3 L\u1ef1c, Th\u00e2n ph\u00e1p", "L\u1eadp t\u1ed5 \u0111\u1ed9i \u0111i luy\u1ec7n c\u00f9ng nhau b\u1ea1n s\u1ebd nh\u1eadn \u0111\u01b0\u1ee3c nhi\u1ec1u kinh nghi\u1ec7m h\u01a1n v\u00e0 l\u00e0m nhi\u1ec7m v\u1ee5 nhanh h\u01a1n", "\u0110\u1ec3 gi\u1ea3m hi\u1ebfu chi\u1ebfn, b\u1ea1n ph\u1ea3i b\u1ecb ng\u01b0\u1eddi kh\u00e1c \u0111\u00e1nh tr\u1ecdng th\u01b0\u01a1ng. V\u00e0o \u0111\u1ea5u tr\u01b0\u1eddng \u0111\u1ec3 thi \u0111\u1ea5u \u0111\u1ec3 gi\u1ea3m", "Khi t\u00e1ch \u0111\u00e1 kh\u1ecfi trang b\u1ecb, b\u1ea1n s\u1ebd thu l\u1ea1i m\u1ed9t n\u1eeda s\u1ed1 \u0111\u00e1 \u00e9p v\u00e0o l\u00fac \u0111\u1ea7u", "B\u1ea1n c\u00f3 th\u1ec3 \u0111\u1ed5i Xu t\u1eeb Y\u00ean, v\u1edbi \u0111i\u1ec1u ki\u1ec7n c\u00f3 \u0111\u1ee7 \u0111i\u1ec3m ho\u1ea1t \u0111\u1ed9ng", "B\u1ea1n s\u1ebd c\u00f3 ph\u1ea7n th\u01b0\u1edfng n\u1ebfu \u0111\u1ea1t th\u00e0nh t\u00edch cao nh\u1ea5t trong \u0111\u1ea5u tr\u01b0\u1eddng m\u1ed7i ng\u00e0y", "\u0110\u1ec3 v\u00e0o khu v\u1ef1c \u0111\u1ea5u tr\u01b0\u1eddng, h\u00e3y t\u00ecm Rikudou \u0111\u1ee9ng \u1edf m\u1ed7i tr\u01b0\u1eddng", "B\u1ea1n c\u00f3 th\u1ec3 t\u0103ng t\u1ec9 l\u1ec7 th\u00e0nh c\u00f4ng khi n\u00e2ng c\u1ea5p \u0111\u1ed3 b\u1eb1ng c\u00e1ch ch\u1ecdn ph\u01b0\u01a1ng ph\u00e1p C\u1ea9n Th\u1eadn, nh\u01b0ng s\u1ebd t\u1ed1n L\u01b0\u1ee3ng", "B\u1ea1n \u0111\u01b0\u1ee3c t\u1eb7ng 10 l\u01b0\u1ee3ng khi \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 20 t\u1ea1i NPC Okanechan", "Ti\u1ec1n L\u01b0\u1ee3ng \u0111\u01b0\u1ee3c chia s\u1ebb cho 3 nh\u00e2n v\u1eadt trong 1 t\u00e0i kho\u1ea3n"};
            y = "Xin ch\u1edd";
            z = "Ch\u1edd";
            A = "Menu";
            String[] stringArray = new String[]{"30 l\u01b0\u1ee3ng", "70 l\u01b0\u1ee3ng", "180 l\u01b0\u1ee3ng", "380 l\u01b0\u1ee3ng", "1000 l\u01b0\u1ee3ng"};
            B = "C\u1ea7n";
            C = "Di chuy\u1ec3n t\u1edbi";
            D = "Khu V\u1ef1c";
            E = "X\u00f3a b\u1ed9 nh\u1edb t\u1ea1m";
            F = new String[]{"Vi\u1ec7t Nam", "Global"};
            String[] stringArray2 = new String[]{"\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a", "\u1797\u17b6\u179f\u17b6\u17a2\u1784\u17cb\u1782\u17d2\u179b\u17c1\u179f"};
            G = "B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t game \u0111\u1ec3 ch\u1ecdn l\u1ea1i khu v\u1ef1c kh\u00f4ng ?";
            H = "\u0110\u00f3ng";
            I = "\u1ea8n";
            J = "T\u1ef1 \u0111\u00e1nh";
            K = "\u0110\u1ee9ng y\u00ean";
            L = "do";
            M = "Kh\u00f3a";
            N = "M\u1edf kh\u00f3a";
            O = "S\u1ed1 seri";
            P = "M\u00e3 th\u1ebb";
            Q = "B\u1eadt";
            R = "T\u1eaft";
            S = "M\u1edf link";
            T = "N\u1ea1p";
            U = "K\u00edch ho\u1ea1t";
            V = "C\u1ea5u h\u00ecnh";
            W = "X\u00f3a";
            X = "Xem";
            Y = "Ti\u1ebfp t\u1ee5c";
            Z = "M\u00e3 r\u01b0\u01a1ng";
            aa = "Th\u1ebb c\u00e0o";
            ab = "Ti\u1ebfp";
            ac = "S\u1eed d\u1ee5ng";
            ad = "S\u1eafp x\u1ebfp";
            ae = "B\u1ecf ra \u0111\u1ea5t";
            af = "T\u00e1ch";
            ag = "Trang b\u1ecb \u0111\u00e3 \u0111\u01b0\u1ee3c t\u00e1ch, b\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c ";
            ah = "C\u00f3";
            ai = "L\u1ea5y ra";
            aj = "B\u1ecf ra";
            ak = "R\u00fat xu";
            al = "C\u1ea5t xu";
            am = "Chuy\u1ec3n xu";
            an = "C\u1ea5t v\u00e0o";
            ao = "B\u00e1n";
            ap = "B\u00e1n nhi\u1ec1u";
            aq = "B\u00e1n h\u1ebft";
            ar = "Gi\u00e1";
            as = "Mua";
            at = "Mua nhi\u1ec1u";
            au = "Kh\u00f4ng";
            av = "Tho\u00e1t";
            aw = "Chat";
            ax = "OK";
            ay = "T\u00e0i kho\u1ea3n";
            az = "M\u1eadt kh\u1ea9u";
            aA = "Nh\u1eadp l\u1ea1i";
            aB = "TK";
            aC = "MK";
            aD = "l\u1ea1i";
            aE = "Xin kh\u1edfi \u0111\u1ed9ng l\u1ea1i game.";
            aF = "Nh\u1eadp l\u1ea1i m\u1eadt kh\u1ea9u";
            aG = "Nh\u1edb";
            aH = "B\u1ecf";
            aI = "\u0110\u0103ng k\u00fd";
            aJ = "Qu\u00ean m\u1eadt kh\u1ea9u";
            aK = "T\u0103ng \u0111\u1ed3 h\u1ecda (cho m\u00e1y m\u1ea1nh)";
            aL = "Gi\u1ea3m \u0111\u1ed3 h\u1ecda (cho m\u00e1y y\u1ebfu)";
            aM = "B\u1ea1n ch\u01b0a nh\u1eadp t\u00ean t\u00e0i kho\u1ea3n";
            aN = "T\u00e0i kho\u1ea3n kh\u00f4ng \u0111\u01b0\u1ee3c c\u00f3 k\u00fd t\u1ef1 \u0111\u1eb7t bi\u1ec7t.";
            aO = "B\u1ea1n ch\u01b0a nh\u1eadp m\u1eadt kh\u1ea9u l\u1ea7n m\u1ed9t.";
            aP = "B\u1ea1n ch\u01b0a nh\u1eadp m\u1eadt kh\u1ea9u l\u1ea7n hai.";
            aQ = "T\u00ean t\u00e0i kho\u1ea3n ph\u1ea3i nhi\u1ec1u h\u01a1n 5 k\u00fd t\u1ef1";
            aR = "M\u1eadt kh\u1ea9u kh\u00f4ng ch\u00ednh x\u00e1c.";
            aS = new String[]{"\u0110\u1ec3 x\u00e1c th\u1ef1c v\u1edbi t\u00ean", "b\u1ea1n ph\u1ea3i \u0111\u1ed3ng \u00fd v\u1edbi quy \u0111\u1ecbnh c\u1ee7a tr\u00f2 ch\u01a1i."};
            aT = "B\u1ea1n \u0111ang s\u1eed d\u1ee5ng m\u1ea1ng g\u00ec? (B\u1ea1n c\u00f3 th\u1ec3 ch\u1ecdn l\u1ea1i t\u1eeb Menu)";
            aU = "C\u00f3 ph\u1ea3i b\u1ea1n d\u00f9ng s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd kh\u00f4ng ?";
            aV = "tin nh\u1eafn ri\u00eang";
            aW = new String[]{"Tin nh\u1eafn gia t\u1ed9c, nh\u00f3m", "Tin nh\u1eafn gia t\u1ed9c", "Tin nh\u1eafn nh\u00f3m"};
            aX = "h\u1ed9 t\u1ed1ng";
            aY = "C\u1ed9ng";
            aZ = "C\u1ed9ng nhi\u1ec1u";
            ba = "\u0111i\u1ec3m ti\u1ec1m n\u0103ng";
            bb = "\u0111i\u1ec3m k\u1ef9 n\u0103ng";
            bc = "\u0110\u1ed3ng \u00fd";
            bd = "H\u1ee7y";
            be = "Danh s\u00e1ch";
            bf = "Th\u1eddi gian";
            bg = "Th\u00e0nh t\u00edch";
            bh = "T\u1ed1i \u0111a";
            bi = "T\u00edch l\u0169y";
            bj = "\u0110ang k\u1ebft n\u1ed1i";
            bk = "\u0110ang \u0111\u0103ng k\u00fd";
            bl = "Ch\u01b0a ho\u00e0n th\u00e0nh";
            bm = "Th\u1eddi gian ho\u00e0n th\u00e0nh";
            bn = "Tinh th\u1ea7n \u0111\u1ed3ng \u0111\u1ed9i";
            bo = "Ch\u1ecdn";
            bp = "B\u1ecf ch\u1ecdn";
            bq = "Ch\u1ecdn v\u1eadt ph\u1ea9m \u0111\u1ec3 xem th\u00f4ng tin.";
            br = "G\u00e1n";
            bs = "K\u1ebft qu\u1ea3";
            bt = "\u0110\u00e1nh gi\u00e1";
            bu = "C\u1ea5p";
            bv = "c\u1ea5p";
            bw = "B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t kh\u00f4ng?";
            bx = "Nh\u00e2n v\u1eadt c\u1ea7n \u0111\u1ed5i t\u00ean";
            by = "M\u00e1y ch\u1ee7 n\u00e0y \u0111ang b\u1ea3o tr\u00ec ho\u1eb7c qu\u00e1 t\u1ea3i. Vui l\u00f2ng th\u1eed l\u1ea1i sau ho\u1eb7c ch\u1ecdn m\u00e1y ch\u1ee7 kh\u00e1c.";
            bz = "T\u1ea1o m\u1edbi";
            bA = "T\u00ean nh\u00e2n v\u1eadt";
            bB = "T\u00ean nh\u00e2n v\u1eadt mu\u1ed1n k\u1ebft b\u1ea1n";
            bC = "\u0111\u00e3 tr\u1edf th\u00e0nh h\u1ea3o h\u1eefu.";
            bD = "\u0110ang t\u1ea3i... ";
            bE = "\u0110\u00f3ng";
            bF = "Nh\u1eadn th\u01b0\u1edfng";
            bG = "r\u01b0\u01a1ng hang \u0111\u1ed9ng";
            bH = "H\u00e0nh trang \u0111\u00e3 \u0111\u01b0\u1ee3c m\u1edf r\u1ed9ng";
            bI = "Kho\u1ea3ng c\u00e1ch h\u1ed9 t\u1ed1ng qu\u00e1 xa, nhi\u1ec7m v\u1ee5 \u0111\u00e3 th\u1ea5t b\u1ea1i";
            bJ = "Ng\u01b0\u1eddi \u0111\u01b0\u1ee3c h\u1ed9 t\u1ed1ng \u0111\u00e3 tr\u1ecdng th\u01b0\u01a1ng, nhi\u1ec7m v\u1ee5 \u0111\u00e3 th\u1ea5t b\u1ea1i";
            bK = "v\u0129nh vi\u1ec5n";
            bL = "Ch\u01b0a n\u00e2ng c\u1ea5p";
            bM = "Kh\u00f4ng th\u1ec3 n\u00e2ng c\u1ea5p";
            bN = "D\u00f9ng v\u1eadt ph\u1ea9m \u0111\u1eb7c bi\u1ec7t \u0111\u1ec3 n\u00e2ng c\u1ea5p";
            bO = "Luy\u1ec7n";
            bP = "Luy\u1ec7n \u0111\u00e1 th\u00e0nh c\u00f4ng, b\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
            bQ = new String[]{"Ch\u1ec9 \u0111\u01b0\u1ee3c chuy\u1ec3n h\u00f3a trang b\u1ecb c\u00f9ng", "lo\u1ea1i v\u00e0 c\u00f9ng c\u1ea5p tr\u1edf l\u00ean.", "S\u1ebd kh\u00f3a trang b\u1ecb sau khi chuy\u1ec3n h\u00f3a."};
            bR = "th\u1ea5t b\u1ea1i, b\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
            bS = "\u0110\u00e3 g\u1eedi tin nh\u1eafn, xin ch\u1edd tin nh\u1eafn x\u00e1c nh\u1eadn.";
            bT = "Kh\u00f4ng th\u1ec3 g\u1edfi tin nh\u1eafn. Xin ki\u1ec3m tra ti\u1ec1n v\u00e0 th\u1eed kh\u1edfi \u0111\u1ed9ng l\u1ea1i game.";
            bU = "Xu \u0111ang g\u1eedi";
            bV = "B\u1eaft \u0111\u1ea7u";
            bW = "Ch\u1ecdn 2 vi\u00ean \u0111\u00e1 tr\u1edf l\u00ean";
            bX = "Ch\u1ecdn Trang B\u1ecb c\u1ea7n t\u00e1ch \u0110\u00e1";
            bY = "Ch\u1ecdn V\u1eadt Ph\u1ea9m v\u00e0 Xu trao \u0111\u1ed5i";
            bZ = "Sang H\u00e0nh Trang \u0111\u1ec3 ch\u1ecdn";
            ca = "\u0110\u1ed5i";
            cb = "\u00f4";
            cc = "\u00f4 th\u1ee9";
            cd = new String[]{"Ph\u00edm Q", "Ph\u00edm W", "Ph\u00edm E"};
            ce = new String[]{"Ph\u00edm 7", "Ph\u00edm 8", "Ph\u00edm 9"};
            cf = new String[][]{{"ng\u1eafn", "c\u00e0i tr\u00e2m", "b\u00fai", "x\u00f9"}, {"\u0111eo b\u0103ng", "b\u00f3 x\u00f9", "samurai", "nh\u00edm"}};
            cg = new String[]{"H\u00e0nh trang", "K\u1ef9 n\u0103ng", "Ti\u1ec1m n\u0103ng", "Th\u00f4ng tin", "Trang b\u1ecb", "Th\u00fa C\u01b0\u1ee1i", "V\u0129 Th\u00fa"};
            ch = new String[]{"Ti\u1ec7m Y Ph\u1ee5c", "H\u00e0nh trang"};
            ci = new String[]{"N\u00f3n", "H\u00e0nh trang"};
            cj = new String[]{"\u00c1o", "H\u00e0nh trang"};
            ck = new String[]{"G\u0103ng tay", "H\u00e0nh trang"};
            cl = new String[]{"Qu\u1ea7n", "H\u00e0nh trang"};
            cm = new String[]{"Gi\u00e0y", "H\u00e0nh trang"};
            cn = new String[]{"D\u00e2y chuy\u1ec1n", "H\u00e0nh trang"};
            co = new String[]{"Nh\u1eabn", "H\u00e0nh trang"};
            cp = new String[]{"Ng\u1ecdc b\u1ed9i", "H\u00e0nh trang"};
            cq = new String[]{"B\u00f9a", "H\u00e0nh trang"};
            cr = new String[]{"Binh kh\u00ed", "H\u00e0nh trang"};
            cs = new String[]{"D\u01b0\u1ee3c ph\u1ea9m", "H\u00e0nh trang"};
            ct = new String[]{"D\u01b0\u1ee3c ph\u1ea9m", "H\u00e0nh trang"};
            cu = new String[]{"Th\u1ee9c \u0103n", "H\u00e0nh trang"};
            cv = new String[]{"Th\u1ee9c \u0103n", "H\u00e0nh trang"};
            cw = new String[]{"N\u00e2ng c\u1ea5p", "H\u00e0nh trang"};
            cx = new String[]{"Gian h\u00e0ng", "H\u00e0nh trang"};
            cy = new String[]{"Chuy\u1ec3n h\u00f3a", "H\u00e0nh trang"};
            cz = new String[]{"Luy\u1ec7n \u0111\u00e1", "H\u00e0nh trang"};
            cA = new String[]{"R\u01b0\u01a1ng \u0111\u1ed3", "H\u00e0nh trang"};
            cB = new String[]{"C\u1eeda h\u00e0ng", "Qu\u1ea7y s\u00e1ch", "Th\u1eddi trang", "Gia T\u1ed9c"};
            cC = new String[]{"B\u1ea3o v\u1eadt"};
            (new String[1])[0] = "C\u1eeda h\u00e0ng gia t\u1ed9c";
            cD = new String[]{"T\u00e1ch \u0110\u00e1", "H\u00e0nh trang"};
            cE = new String[]{"Giao d\u1ecbch", "H\u00e0nh trang"};
            cF = new String[]{"Luy\u1ec7n th\u1ea1ch", "H\u00e0nh trang"};
            cG = new String[]{"D\u1ecbch chuy\u1ec3n", "H\u00e0nh trang"};
            cH = new String[]{"Tinh luy\u1ec7n", "H\u00e0nh trang"};
            cI = new String[]{"Kh\u1ea3m ng\u1ecdc", "H\u00e0nh trang"};
            cJ = new String[]{"Luy\u1ec7n ng\u1ecdc", "H\u00e0nh trang"};
            cK = new String[]{"Ch\u1ebf \u0110\u1ed3", "H\u00e0nh trang"};
            cM = new String[]{"G\u1ecdt ng\u1ecdc", "H\u00e0nh trang"};
            cL = new String[]{"Giao \u0111\u1ed3", "H\u00e0nh trang"};
            cN = new String[]{"Th\u00e1o ng\u1ecdc", "H\u00e0nh trang"};
            n = "Ta s\u1ebd l\u00e0m gi\u1ea3m \u0111i ch\u1ec9 s\u1ed1 b\u1ea5t l\u1ee3i tr\u00ean vi\u00ean ng\u1ecdc n\u00e0y.";
            o = "Ta s\u1ebd gi\u00fap ng\u01b0\u01a1i th\u00e1o b\u1ecf ng\u1ecdc kh\u1ea3m tr\u00ean trang b\u1ecb.";
            cO = new String[]{"- S\u1eed d\u1ee5ng Y\u00ean, n\u1ebfu kh\u00f4ng \u0111\u1ee7 d\u00f9ng Xu", "- Qua trang H\u00e0nh Trang \u0111\u1ec3 ch\u1ecdn \u0110\u00e1", "- S\u1ed1 l\u01b0\u1ee3ng \u0111\u00e1 t\u1eeb 2 \u0111\u1ebfn 24"};
            cP = new String[]{"- S\u1eed d\u1ee5ng Y\u00ean, n\u1ebfu kh\u00f4ng \u0111\u1ee7 d\u00f9ng Xu", "- N\u00e2ng c\u1ea5p c\u1ea9n th\u1eadn c\u1ea7n d\u00f9ng l\u01b0\u1ee3ng", "- Ch\u1ec9 ch\u1ecdn Trang B\u1ecb v\u00e0 \u0110\u00e1", "Trang b\u1ecb \u0111\u00e3 \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p t\u1ed1i \u0111a"};
            String[] stringArray3 = new String[]{"- Qua H\u00e0nh Trang \u0111\u1ec3 ch\u1ecdn Trang B\u1ecb", " Sau khi t\u00e1ch xong s\u1ebd nh\u01b0 l\u00fac \u0111\u1ea7u", "Trang b\u1ecb \u0111\u00e3 \u0111\u01b0\u1ee3c t\u00e1ch"};
            cQ = new String[]{"- S\u1eed d\u1ee5ng Y\u00ean, n\u1ebfu kh\u00f4ng \u0111\u1ee7 d\u00f9ng Xu", "- Ch\u1ec9 ch\u1ecdn Trang B\u1ecb v\u00e0 Ng\u1ecdc"};
            cR = "Kh\u00f3a G.D\u1ecbch";
            cS = "- Luy\u1ec7n th\u00e0nh \u0110\u00e1 c\u1ea5p";
            cT = "- C\u1ea7n: # y\u00ean";
            cU = "- C\u1ea7n: # l\u01b0\u1ee3ng";
            cV = "- C\u1ea7n: # xu";
            cW = "- X\u00e1c xu\u1ea5t th\u00e0nh c\u00f4ng";
            cX = "(th\u00e0nh c\u00f4ng ";
            cY = "B\u1ea1n c\u00f3 mu\u1ed1n b\u1ecf v\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng?";
            cZ = "C\u1ed9ng";
            db = "\u0110\u00e3 kh\u00f3a";
            dc = "Ti\u00eau di\u1ec7t";
            dd = "B\u1eaft t\u00e0 th\u00fa";
            de = "Ti\u00eau di\u1ec7t tinh anh";
            df = "Ti\u00eau di\u1ec7t th\u1ee7 l\u0129nh";
            dg = "H\u1ed9 t\u1ed1ng tr\u1ebb l\u1ea1c";
            dh = "Kh\u00f4ng kh\u00f3a";
            di = "H\u1ea1n s\u1eed d\u1ee5ng";
            dj = "Gi\u00e1 b\u00e1n: # y\u00ean";
            dk = "Gi\u00e1 mua: # xu";
            dl = "Gi\u00e1 mua: # xu gia t\u1ed9c";
            dm = "Gi\u00e1 mua: # y\u00ean";
            dn = "Gi\u00e1 mua: # l\u01b0\u1ee3ng";
            do = "l\u01b0\u1ee3ng";
            dp = "Ch\u01b0a c\u00f3";
            dq = "C\u1ea5p k\u1ebf: c\u1ea5p #";
            dr = "C\u1ea5p hi\u1ec7n t\u1ea1i: c\u1ea5p #";
            ds = "C\u1ea5p t\u1ed1i \u0111a";
            dt = "\u0110\u00e3 \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 t\u1ed1i \u0111a";
            du = "Y\u00eau c\u1ea7u: tr\u00ecnh \u0111\u1ed9 c\u1ea5p";
            dv = "L\u1edbp: ";
            dw = new String[]{"Ch\u00ednh tuy\u1ebfn", "Ph\u1ee5 tuy\u1ebfn"};
            dx = "Nhi\u1ec7m v\u1ee5";
            dy = "Nh\u1eadn NV \u1edf";
            dz = "B\u1ea1ch gi\u1ea3";
            dA = "H\u1eafc gi\u1ea3";
            dB = "Ho\u00e0ng gi\u1ea3";
            dC = "Trung l\u1eadp";
            dD = "Nh\u00f3m";
            dE = "T\u00ecm Nh\u00f3m";
            dF = "\u0110i\u1ec3m hi\u1ebfu chi\u1ebfn c\u1ee7a b\u1ea1n hi\u1ec7n t\u1ea1i l\u00e0 ";
            dG = new String[]{"B\u1ea1n b\u00e8", "Th\u00f9 \u0110\u1ecbch"};
            dH = "B\u1ea1n ch\u01b0a k\u1ebft b\u1ea1n v\u1edbi ai";
            dI = "ch\u1edd x\u00e1c nh\u1eadn";
            dJ = "\u0111\u00e3 th\u00eam b\u1ea1n v\u00e0o danh s\u00e1ch b\u1ea1n b\u00e8";
            dK = "B\u1ea1n \u0111\u00e3 th\u00eam";
            dL = "v\u00e0o danh s\u00e1ch";
            dM = "B\u1ea1n v\u00e0";
            dN = new String[]{"C\u1eeda h\u00e0ng", "B\u1ea3n th\u00e2n", "B\u1ea3n \u0111\u1ed3", "T\u1ed5ng h\u1ee3p", "Tho\u00e1t", "Trang s\u1ee9c", "T\u00ednh n\u0103ng", "D\u01b0\u1ee3c kh\u00f3a", "D\u01b0\u1ee3c ph\u1ea9m", "T\u1ea1p h\u00f3a kh\u00f3a", "T\u1ea1p h\u00f3a", "C\u01b0\u1eddng h\u00f3a", "Luy\u1ec7n h\u00f3a", "Luy\u1ec7n h\u00f3a kh\u00f3a", "Th\u1ee7 kh\u1ed1", "T\u00e1ch trang b\u1ecb", "Khu v\u1ef1c", "Giao d\u1ecbch", "Tin nh\u1eafn", "Ch\u1ecdn Nh\u00e2n v\u1eadt"};
            dO = new String[]{"H\u1ed7 tr\u1ee3 b\u1ecb \u0111\u1ed9ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng", "Ch\u1ee7 \u0111\u1ed9ng s\u1eed d\u1ee5ng"};
            String[] stringArray4 = new String[]{"B\u1ea1n \u0111\u00e3 h\u1ebft \u0111i\u1ec3m k\u1ef9 n\u0103ng. Vui l\u00f2ng \u0111\u00e1nh l\u00ean level \u0111\u1ec3 c\u00f3 th\u00eam \u0111i\u1ec3m k\u1ef9 n\u0103ng", "B\u1ea1n \u0111\u00e3 h\u1ebft \u0111i\u1ec3m ti\u1ec1m n\u0103ng. Vui l\u00f2ng \u0111\u00e1nh l\u00ean level \u0111\u1ec3 c\u00f3 th\u00eam \u0111i\u1ec3m ti\u1ec1m n\u0103ng"};
            dP = new String[]{"Nh\u00e2n v\u1eadt: ", "Hi\u1ebfu chi\u1ebfn: ", "Tr\u00ecnh \u0111\u1ed9: ", "L\u1edbp: ", "", "HP: ", "MP: ", "T\u1ed1c \u0111\u1ed9: ", "T\u1ea5n c\u00f4ng: ", "H\u1ecfa ch\u1ed1ng: ", "B\u0103ng ch\u1ed1ng: ", "Phong ch\u1ed1ng: ", "Gi\u1ea3m s\u00e1t th\u01b0\u01a1ng: ", "\u0110\u1ed9 ch\u00ednh x\u00e1c: ", "Kh\u1ea3 n\u0103ng n\u00e9 \u0111\u00f2n: ", "Ch\u00ed m\u1ea1ng: ", "Ph\u1ea3n \u0111\u00f2n c\u1eadn chi\u1ebfn: ", "C\u01b0\u1eddng kh\u1eafc: ", "H\u1ea1 kh\u1eafc: ", "\u0110i\u1ec3m ho\u1ea1t \u0111\u1ed9ng: "};
            dQ = " l\u1ea7n";
            dR = new String[]{"H\u1ecdc Gi\u1ea3", "H\u1ea1 nh\u1eabn", "Trung Nh\u1eabn", "Th\u01b0\u1ee3ng Nh\u1eabn", "Nh\u1eabn Gi\u1ea3"};
            dS = new String[]{"\u0110i\u1ec3m ho\u1ea1t \u0111\u1ed9ng: ", "Danh v\u1ecdng v\u0169 kh\u00ed: ", "Danh v\u1ecdng d\u00e2y chuy\u1ec1n: ", "Danh v\u1ecdng nh\u1eabn: ", "Danh v\u1ecdng ng\u1ecdc b\u1ed9i: ", "Danh v\u1ecdng b\u00f9a: ", "Danh v\u1ecdng n\u00f3n: ", "Danh v\u1ecdng \u00e1o: ", "Danh v\u1ecdng g\u0103ng tay: ", "Danh v\u1ecdng qu\u1ea7n: ", "Danh v\u1ecdng gi\u00e0y: ", "Ho\u00e0n th\u00e0nh NV m\u1ed7i ng\u00e0y: ", "Truy b\u1eaft T\u00e0 Th\u00fa c\u00f2n: ", "H\u1ecdc s\u00e1ch ti\u1ec1m n\u0103ng s\u01a1: ", "H\u1ecdc s\u00e1ch k\u1ef9 n\u0103ng s\u01a1: ", "Gia t\u1ed9c: ", "V\u00e0o hang \u0111\u1ed9ng c\u00f2n: ", "\u0110i\u1ec3m tinh t\u00fa: ", "S\u1ed1 l\u1ea7n \u0103n b\u00e1nh phong l\u00f4i: ", "S\u1ed1 l\u1ea7n \u0103n b\u00e1nh b\u0103ng h\u1ecfa: "};
            dT = new String[]{"T\u00ean: ", "Gi\u1edbi t\u00ednh: ", "T\u00f3c: "};
            dU = new String[]{"N\u1eef", "Nam"};
            dV = new String[]{"S\u1ee9c m\u1ea1nh", "Th\u00e2n ph\u00e1p", "Th\u1ec3 l\u1ef1c", "Chakra"};
            String[] stringArray5 = new String[]{"S\u1ee9c m\u1ea1nh", "Nhanh nh\u1eb9n", "S\u1ee9c kh\u1ecfe", "Tr\u00ed tu\u1ec7"};
            dW = "Ch\u01b0a c\u00f3 ai c\u1eebu s\u00e1t b\u1ea1n";
            dX = "B\u1ea1n \u0111\u00e3 th\u1eafng #.";
            dY = "B\u1ea1n \u0111\u00e3 thua #.";
            dZ = "Cu\u1ed9c so t\u00e0i gi\u1eefa b\u1ea1n v\u00e0 # \u0111\u00e3 k\u1ebft th\u00fac";
            ea = new String[]{"", "Tinh Anh", "Th\u1ee7 L\u0129nh", "T\u00e0 Th\u00fa"};
            eb = " b\u1eaft \u0111\u1ea7u c\u1eebu s\u00e1t b\u1ea1n";
            ec = "\u0110i\u1ec3m ti\u1ec1m n\u0103ng";
            ed = "\u0110i\u1ec3m k\u1ef9 n\u0103ng";
            ee = "Kh\u00f4ng \u0111\u1ee7 MP \u0111\u1ec3 s\u1eed d\u1ee5ng";
            ef = "Ch\u1ec9 \u0111\u01b0\u1ee3c v\u1eadt ph\u1ea9m kh\u00f4ng kh\u00f3a";
            eg = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn v\u1eadt ph\u1ea9m kh\u00f4ng kh\u00f3a v\u00e0 kh\u00f4ng c\u00f3 h\u1ea1n s\u1eed d\u1ee5ng";
            eh = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0110\u00e1 \u0111\u1ec3 luy\u1ec7n c\u1ea5p";
            ei = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0110\u00e1, Trang b\u1ecb, v\u00e0 B\u1ea3o hi\u1ec3m \u0111\u1ec3 n\u00e2ng c\u1ea5p";
            ej = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn Trang b\u1ecb v\u00e0 v\u1eadt ph\u1ea9m Ho\u00e1n chuy\u1ec3n.";
            ek = "Trang b\u1ecb kh\u00f4ng th\u1ec3 n\u00e2ng c\u1ea5p";
            el = "Trang b\u1ecb \u0111\u00e3 n\u00e2ng c\u1ea5p t\u1ed1i \u0111a";
            em = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn trang b\u1ecb \u0111\u00e3 n\u00e2ng c\u1ea5p m\u1edbi c\u00f3 th\u1ec3 t\u00e1ch \u0111\u01b0\u1ee3c";
            en = "V\u1eadt ph\u1ea9m giao d\u1ecbch \u0111\u00e3 \u0111\u1ea7y";
            eo = "S\u1ed1 l\u01b0\u1ee3ng \u0111\u00e3 \u0111\u1ea7y";
            ep = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 \u0111i\u1ec3m c\u1ed9ng";
            eq = "B\u1ea1n ch\u01b0a nh\u1eadp \u0111i\u1ec3m c\u1ed9ng";
            er = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin lo\u1ea1i th\u1ebb";
            es = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin m\u1ec7nh gi\u00e1.";
            et = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin s\u1ed1 seri";
            eu = "B\u1ea1n ch\u01b0a nh\u1eadp th\u00f4ng tin kho\u1ea3ng th\u1eddi gian n\u1ea1p.";
            ev = "B\u1ea1n ch\u01b0a nh\u1eadp v\u00e0o t\u00ean c\u1ea7n th\u00eam";
            ew = "Nh\u1eadp \u0111i\u1ec3m";
            ex = "Nh\u1eadp Xu";
            ey = "Nh\u1eadp s\u1ed1 l\u01b0\u1ee3ng";
            ez = "T\u00ean t\u00e0i kho\u1ea3n";
            eA = "Xu";
            eB = "Y\u00ean";
            eC = "L\u01b0\u1ee3ng";
            eD = "C\u1ea5t v\u00e0o h\u00e0nh trang";
            eE = "B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n b\u00e3i nhi\u1ec7m ch\u1ee9c v\u1ee5 c\u1ee7a ng\u01b0\u1eddi n\u00e0y kh\u00f4ng?";
            eF = "Tr\u1ee5c xu\u1ea5t th\u00e0nh vi\u00ean s\u1ebd b\u1ecb gi\u1ea3m ng\u00e2n s\u00e1ch gia t\u1ed9c (xem chi ti\u1ebft t\u1ea1i Npc Kanata). B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n tr\u1ee5c xu\u1ea5t ng\u01b0\u1eddi n\u00e0y kh\u00f4ng?";
            eG = "T\u1ef1 r\u1eddi kh\u1ecfi gia t\u1ed9c s\u1ebd b\u1ecb gi\u1ea3m xu trong h\u00e0nh trang (xem chi ti\u1ebft t\u1ea1i Npc Kanata). B\u1ea1n c\u00f3 mu\u1ed1n r\u1eddi kh\u1ecfi kh\u00f4ng?";
            eH = "Sau khi s\u1eed d\u1ee5ng v\u1eadt ph\u1ea9m s\u1ebd b\u1ecb kh\u00f3a. B\u1ea1n c\u00f3 mu\u1ed1n s\u1eed d\u1ee5ng kh\u00f4ng?";
            eI = "Sau khi b\u00e1n v\u1eadt ph\u1ea9m s\u1ebd kh\u00f4ng th\u1ec3 ph\u1ee5c h\u1ed3i. B\u1ea1n c\u00f3 mu\u1ed1n b\u00e1n v\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng?";
            eJ = new String[][]{{"n\u00f3n"}, {"v\u0169", "kh\u00ed"}, {"\u00e1o"}, {"v\u00f2ng", "c\u1ed5"}, {"g\u0103ng", "tay"}, {"nh\u1eabn"}, {"qu\u1ea7n"}, {"b\u1ed9i"}, {"gi\u00e0y"}, {"b\u00f9a"}, {"th\u00fa", "nu\u00f4i"}, {"m\u1eb7t", "n\u1ea1"}, {"ninja", "yoroi"}, {"gia", "t\u1ed9c"}, {"ch\u01b0a", "m\u1edf"}, {"b\u00ed", "k\u00edp"}, {"\u00e1o", "gi\u00e1p"}, {"y\u00ean", ""}, {"c\u01b0\u01a1ng", ""}, {"trang", "s\u1ee9c"}, {"\u0111\u1ed9ng", "c\u01a1"}, {"\u0111\u1ecbnh", "v\u1ecb"}, {"b\u1ed9", "\u0111k"}, {"b\u00ecnh", "nitro"}, {"m\u00f3ng", "vu\u1ed1t"}, {"d\u00e2y", "chuy\u1ec1n"}, {"th\u00fa", "b\u1ea3o"}, {"x\u00edch", ""}};
            eK = new String[]{"Ch\u01b0a v\u00e0o tr\u01b0\u1eddng", "Tr\u01b0\u1eddng: Hirosaki", "Tr\u01b0\u1eddng: Ookaza", "Tr\u01b0\u1eddng: Haruna"};
            eL = new String[]{"", "Thu\u1ed9c t\u00ednh: H\u1ecfa", "Thu\u1ed9c t\u00ednh: Th\u1ee7y", "Thu\u1ed9c t\u00ednh: Phong", "", "", ""};
            eM = "B\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
            eN = "B\u1ea1n ch\u01b0a nh\u1eadp v\u00e0o s\u1ed1 l\u01b0\u01a1ng";
            eO = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 chuy\u1ec3n.";
            eP = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 c\u1ea5t";
            eQ = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 r\u00fat";
            eR = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 s\u1ed1 l\u01b0\u1ee3ng \u0111\u1ec3 b\u00e1n";
            String[] stringArray6 = new String[]{"Luy\u1ec7n \u0111\u00e1 th\u00e0nh c\u00f4ng", "Luy\u1ec7n \u0111\u00e1 th\u1ea5t b\u1ea1i"};
            eS = new String[]{"Th\u00e0nh c\u00f4ng, trang b\u1ecb \u0111\u01b0\u1ee3c l\u00ean c\u1ea5p ", "Th\u1ea5t b\u1ea1i, trang b\u1ecb tr\u1edf v\u1ec1 c\u1ea5p ", "Trang b\u1ecb \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p t\u1ed1i \u0111a", "Trang b\u1ecb c\u1ea5p"};
            eT = new String[]{"Kh\u1ea3m ng\u1ecdc th\u00e0nh c\u00f4ng", "Kh\u1ea3m ng\u1ecdc th\u1ea5t b\u1ea1i"};
            eU = "th\u00e1ng";
            eV = "tu\u1ea7n";
            eW = "ng\u00e0y";
            eX = "gi\u1edd";
            eY = "gi\u00e2y";
            eZ = "ph\u00fat";
            fa = "\u1ea2nh h\u01b0\u1edfng";
            fb = "Ph\u1ea1m vi";
            fc = "MP m\u1ea5t";
            fd = "Kho\u1ea3ng c\u00e1ch thi tri\u1ec3n";
            fe = "Ph\u1ea3i c\u00f3 t\u1eeb 2 vi\u00ean \u0111\u00e1 tr\u1edf l\u00ean m\u1edbi c\u00f3 th\u1ec3 luy\u1ec7n \u0111\u01b0\u1ee3c";
            ff = "Gi\u1edbi t\u00ednh kh\u00f4ng ph\u00f9 h\u1ee3p";
            fg = "Kh\u00f4ng c\u00f3 ng\u01b0\u1eddi ch\u01a1i kh\u00e1c";
            fh = "Tr\u00ecnh \u0111\u1ed9 c\u1ee7a b\u1ea1n ch\u01b0a \u0111\u1ea1t y\u00eau c\u1ea7u";
            fi = "\u0110\u00e1 \u0111\u00e3 \u0111\u1ea1t c\u1ea5p \u0111\u1ed9 t\u1ed1i \u0111a";
            fj = "\u0110\u00e1 sau khi luy\u1ec7n c\u1ea5p s\u1ebd b\u1ecb kh\u00f3a. B\u1ea1n c\u00f3 mu\u1ed1n ti\u1ebfp t\u1ee5c kh\u00f4ng?";
            fk = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 luy\u1ec7n \u0111\u00e1";
            fl = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 l\u01b0\u1ee3ng \u0111\u1ec3 n\u00e2ng c\u1ea5p trang b\u1ecb";
            fm = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 xu ho\u1eb7c y\u00ean \u0111\u1ec3 n\u00e2ng c\u1ea5p trang b\u1ecb";
            fn = "Nhi\u1ec1u \u0111\u00e1 qu\u00e1 s\u1ebd b\u1ecb l\u00e3ng ph\u00ed. B\u1ea1n c\u00f3 ch\u1eafc ch\u1eafn mu\u1ed1n n\u00e2ng c\u1ea5p?";
            fo = "Sau khi n\u00e2ng c\u1ea5p trang b\u1ecb s\u1ebd b\u1ecb kh\u00f3a. B\u1ea1n c\u00f3 mu\u1ed1n ti\u1ebfp t\u1ee5c kh\u00f4ng?";
            fp = "Kh\u00f4ng th\u1ec3 t\u00e1ch trang b\u1ecb ch\u01b0a n\u00e2ng c\u1ea5p";
            fq = "H\u00e0nh trang kh\u00f4ng \u0111\u1ee7 ch\u1ed7 tr\u1ed1ng";
            fr = "B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n t\u00e1ch kh\u00f4ng?";
            fs = "B\u1ea1n c\u00f3 th\u1eadt s\u1ef1 mu\u1ed1n chuy\u1ec3n h\u00f3a kh\u00f4ng?";
            ft = "m\u1eddi b\u1ea1n giao d\u1ecbch. B\u1ea1n c\u00f3 mu\u1ed1n giao d\u1ecbch kh\u00f4ng?";
            fu = "m\u1eddi b\u1ea1n v\u00e0o t\u1ed9c. B\u1ea1n c\u00f3 mu\u1ed1n l\u00e0 th\u00e0nh vi\u00ean c\u1ee7a gia t\u1ed9c '#' kh\u00f4ng?";
            fv = "mu\u1ed1n xin v\u00e0o gia t\u1ed9c. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            fw = "mu\u1ed1n t\u1ef7 th\u00ed v\u1edbi b\u1ea1n. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            fy = "m\u1eddi b\u1ea1n v\u00e0o nh\u00f3m. B\u1ea1n c\u00f3 mu\u1ed1n v\u00e0o kh\u00f4ng?";
            fz = "mu\u1ed1n xin v\u00e0o nh\u00f3m. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            fA = "Chuy\u1ec3n h\u00f3a trang b\u1ecb th\u00e0nh c\u00f4ng.";
            fB = new String[]{"Gi\u1edbi t\u00ednh: n\u1eef", "Gi\u1edbi t\u00ednh: nam"};
            fC = "Khu v\u1ef1c";
            fD = "D\u00e2n s\u1ed1";
            fE = "Nh\u00f3m";
            fF = "Hi\u1ec7n t\u1ea1i b\u1ea1n kh\u00f4ng v\u00e0o nh\u00f3m n\u00e0o";
            fG = "l\u1ea7n";
            fH = new String[]{"Th\u00f4ng tin", "Th\u00e0nh vi\u00ean", "Nh\u00e0 Kho", "Th\u1ed1ng K\u00ea", "Th\u1ea7n Th\u00fa"};
            fI = new String[]{"Gia t\u1ed9c: ", "T\u1ed9c tr\u01b0\u1edfng: ", "Th\u00e0nh vi\u00ean: ", "C\u1ea5p: ", "Kinh nghi\u1ec7m: ", "Ng\u00e2n s\u00e1ch: ", "Th\u00e0nh l\u1eadp: ", "C\u1ed1ng hi\u1ebfn: ", "Ph\u00ed duy tr\u00ec: ", "Ph\u00ed n\u00e2ng c\u1ea5p: ", "V\u00e0o L\u00e3nh \u0110\u1ecba Gia T\u1ed9c: c\u00f2n ", "C\u1ed1ng hi\u1ebfn tu\u1ea7n: ", "S\u1eed d\u1ee5ng l\u1ec7nh b\u00e0i c\u00f2n: "};
            fJ = new String[]{"xu l\u00fac", "Th\u00e0nh l\u1eadp gia t\u1ed9c, ng\u00e2n s\u00e1ch nh\u1eadn", "b\u1ecb tr\u1ee5c xu\u1ea5t, ng\u00e2n s\u00e1ch tr\u1eeb", "\u0111\u00f3ng g\u00f3p qu\u1ef9 gia t\u1ed9c, ng\u00e2n s\u00e1ch t\u0103ng", "r\u00fat qu\u1ef9 gia t\u1ed9c, ng\u00e2n s\u00e1ch gi\u1ea3m", "Thu ph\u00ed duy tr\u00ec gia t\u1ed9c, ng\u00e2n s\u00e1ch gi\u1ea3m", "n\u00e2ng c\u1ea5p gia t\u1ed9c, ng\u00e2n s\u00e1ch gi\u1ea3m"};
            fK = "Hi\u1ec7n t\u1ea1i b\u1ea1n ch\u01b0a gia nh\u1eadp gia t\u1ed9c";
            fL = "Ph\u00e1t cho Th\u00e0nh vi\u00ean";
            fM = new String[][]{{"Tr\u01b0\u1eddng Hirosaki"}, {"Tr\u01b0\u1eddng Haruna"}, {"Tr\u01b0\u1eddng Ookaza"}, {"L\u00e0ng", "L\u00e0ng Kojin", "L\u00e0ng Sanzu", "L\u00e0ng Tone", "L\u00e0ng ch\u00e0i", "L\u00e0ng Chakumi", "L\u00e0ng Echigo", "L\u00e0ng Oshin"}, {"Khu v\u1ef1c"}};
            fN = new String[]{"N\u00f3n", "Nh\u00e2n", "\u00c1o", "D\u00e2y chuy\u1ec1n", "G\u0103ng tay", "Nh\u1eabn", "Qu\u1ea7n", "Ng\u1ecdc b\u1ed9i", "Gi\u00e0y", "B\u00f9a"};
            fO = new String[]{"K\u00edch \u1ea9n", "K\u00edch c\u1ea5p \u0111\u1ed9"};
            fP = new String[]{"", "H\u1ecfa", "Th\u1ee7y", "Phong"};
            fQ = new String[]{"Nh\u00e2n v\u1eadt", "Level", ""};
            String[] stringArray7 = new String[]{"Ch\u01b0a c\u00f3 t\u00e0i kho\u1ea3n xin", "ch\u1ecdn menu \u0111\u0103ng k\u00fd."};
            fR = "V\u00f4 chi\u00eau th\u1eafng h\u1eefu chi\u00eau. Hi\u1ec7n t\u1ea1i b\u1ea1n ch\u01b0a c\u00f3 chi\u00eau \u0111\u1ec3 \u0111\u00e1nh.";
            fS = "B\u1ea1n ch\u01b0a c\u00f3 v\u0169 kh\u00ed. Xin v\u00e0o Menu/B\u1ea3n Th\u00e2n/Trang b\u1ecb \u0111\u1ec3 ki\u1ec3m tra";
            fT = "V\u1eadt ph\u1ea9m \u0111\u00e3 b\u1ecb kh\u00f3a";
            fU = "V\u1eadt ph\u1ea9m, trang b\u1ecb v\u00e0 \u0111\u00e1";
            fV = "M\u1ee9c gi\u00e1 (xu)";
            fW = "M\u1ee9c gi\u00e1 (y\u00ean)";
            fX = "\u0110\u00e3 h\u1ebft hi\u1ec7u qu\u1ea3 th\u1ee9c \u0103n";
            fY = "Level c\u1ee7a b\u1ea1n kh\u00f4ng \u0111\u1ee7 \u0111\u1ec3 s\u1eed d\u1ee5ng";
            fZ = "\u0110\u00e3 h\u1ebft b\u00ecnh MP";
            ga = "\u0110\u00e3 h\u1ebft b\u00ecnh HP";
            gb = new String[]{"Giao d\u1ecbch", "T\u1ef7 th\u00ed", "C\u1eebu s\u00e1t", "K\u1ebft b\u1ea1n", "M\u1eddi v\u00e0o nh\u00f3m", "Ph\u1ee5c h\u1ed3i", "Xem th\u00f4ng tin", "Chat ri\u00eang", "M\u1eddi v\u00e0o t\u1ed9c", "Xin v\u00e0o t\u1ed9c", "Ch\u1eb7n xin v\u00e0o t\u1ed9c", "T\u1ef1 H\u1ed3i Sinh", "C\u1ea5m Chat"};
            gc = "B\u1ea1n \u0111ang \u1edf khu v\u1ef1c n\u00e0y";
            gd = new String[]{"H\u00e3y \u0111i t\u00ecm ", " \u1edf ", " \u0111\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5.", "B\u1ea1n \u0111\u00e3 ho\u00e0n th\u00e0nh h\u1ebft nhi\u1ec7m v\u1ee5 phi\u00ean b\u1ea3n n\u00e0y, vui l\u00f2ng ch\u1edd cho \u0111\u1ebfn khi ra phi\u00ean b\u1ea3n ti\u1ebfp theo."};
            ge = new String[]{"Ki\u1ec7t s\u1ee9c", "\u0110\u1ee9ng nh\u00ecn", "Quay v\u1ec1", "H\u1ed3i sinh t\u1ea1i ch\u1ed7 (1 l\u01b0\u1ee3ng)"};
            gf = "Sau khi gia nh\u1eadp v\u00e0o l\u1edbp h\u1ecdc, th\u00ec c\u00f3 th\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5 t\u1eeb hi\u1ec7u tr\u01b0\u1edfng";
            gg = "T\u1ea1o nh\u00f3m";
            gh = "R\u1eddi nh\u00f3m";
            gi = "Nh\u00f3m tr\u01b0\u1edfng";
            gj = "Kh\u00f3a nh\u00f3m";
            gk = "M\u1edf nh\u00f3m";
            gl = "Xin gia nh\u1eadp";
            gm = "T\u00ecm l\u1ea1i";
            gn = "Hi\u1ec7n t\u1ea1i b\u1ea1n ch\u01b0a c\u00f3 nh\u00f3m";
            go = "Ch\u01b0a c\u00f3 th\u00f4ng tin";
            gp = "Hi\u1ec7n t\u1ea1i kh\u00f4ng t\u00ecm th\u1ea5y nh\u00f3m";
            gq = new String[]{"PK Th\u01b0\u1eddng", "PK Phe", "PK Bang", "PK \u0110\u1ed3 S\u00e1t"};
            gr = new String[]{"Tr\u1ea1ng th\u00e1i PK", "B\u1ea1n b\u00e8", "Th\u00f9 \u0110\u1ecbch", "Nh\u00f3m", "T\u00ecm nh\u00f3m", "Gia t\u1ed9c", "B\u1ea3o v\u1ec7 t\u00e0i kho\u1ea3n", "T\u1ef1 \u0111\u1ed9ng"};
            gs = new String[]{"B\u1ea3n \u0111\u1ed3", "Nhi\u1ec7m v\u1ee5", "Gia t\u1ed9c"};
            gt = new String[]{"T\u1ed9c tr\u01b0\u1edfng", "T\u1ed9c ph\u00f3", "Tr\u01b0\u1edfng l\u00e3o", "\u01afu t\u00fa", "Th\u00e0nh vi\u00ean"};
            gu = new String[]{"(TT)", "(TP)", "(TL)", "(UT)"};
            gv = new String[]{"Ch\u1ec9 hi\u1ec7n Online", "R\u1eddi kh\u1ecfi", "Th\u00f4ng b\u00e1o", "\u0110\u00f3ng g\u00f3p", "R\u00fat qu\u1ef9", "N\u00e2ng C\u1ea5p", "M\u1eddi v\u00e0o l\u00e3nh \u0111\u1ecba", "M\u1eddi v\u00e0o Gia t\u1ed9c chi\u1ebfn", "Khai m\u1edf"};
            gw = "SX theo C.Hi\u1ebfn tu\u1ea7n";
            gx = new String[]{"Tr\u1ee5c xu\u1ea5t", "Nh\u01b0\u1eddng", "K\u1ebft b\u1ea1n"};
            String[] stringArray8 = new String[]{"T\u1ed9c ph\u00f3", "Tr\u01b0\u1edfng l\u00e3o"};
            gy = " \u0111\u01b0\u1ee3c l\u00ean l\u00e0m nh\u00f3m tr\u01b0\u1edfng.";
            gz = "B\u1ea1n b\u1ecb \u0111u\u1ed5i ra kh\u1ecfi nh\u00f3m";
            gA = "M\u1eddi v\u00e0o nh\u00f3m";
            gB = "Th\u00eam";
            gC = "V\u0169 kh\u00ed kh\u00f4ng th\u00edch h\u1ee3p.";
            gD = "B\u1ea1n c\u00f3 mu\u1ed1n x\u00f3a ng\u01b0\u1eddi n\u00e0y ra kh\u1ecfi danh s\u00e1ch?";
            gE = new String[]{"B\u1ea1n ph\u1ea3i v\u00e0o tr\u01b0\u1eddng \u0111\u1ec3 t\u0103ng \u0111i\u1ec3m"};
            gF = new String[]{"S\u1ee9c m\u1ea1nh = T\u1ea5n c\u00f4ng", "Th\u00e2n ph\u00e1p = n\u00e9,ch\u00ednh x\u00e1c", "Th\u1ec3 l\u1ef1c = HP", "Chakra = MP"};
            gG = new String[]{"Kh\u00f4ng c\u1ea7n t\u0103ng s\u1ee9c m\u1ea1nh", "Th\u00e2n ph\u00e1p = n\u00e9,ch\u00ednh x\u00e1c", "Th\u1ec3 l\u1ef1c = HP", "Chakra = T\u1ea5n c\u00f4ng, MP"};
            String[] stringArray9 = new String[]{"S\u1ee9c m\u1ea1nh = 10 t\u1ea5n c\u00f4ng", "Nhanh nh\u1eb9n = 10 ch\u00ednh x\u00e1c", "S\u1ee9c kh\u1ecfe = 10s tri\u1ec7u h\u1ed3i", "Tr\u00ed tu\u1ec7 = 1 MP"};
            gH = "\u0110\u00f3ng tab hi\u1ec7n t\u1ea1i";
            gI = new String[]{"C\u00f4ng c\u1ed9ng", "B\u1ea1n c\u00f3 th\u1ec3 chat v\u1edbi ng\u01b0\u1eddi \u0111\u1ee9ng g\u1ea7n t\u1ea1i \u0111\u00e2y"};
            gJ = new String[]{"Chung nh\u00f3m", "B\u1ea1n c\u00f3 th\u1ec3 chat v\u1edbi ng\u01b0\u1eddi trong c\u00f9ng nh\u00f3m t\u1ea1i \u0111\u00e2y"};
            gK = new String[]{"K\u00eanh th\u1ebf gi\u1edbi", "B\u1ea1n m\u1ea5t 5 l\u01b0\u1ee3ng m\u1ed7i l\u1ea7n chat k\u00eanh th\u1ebf gi\u1edbi.", "T\u1ea5t c\u1ea3 ng\u01b0\u1eddi \u0111ang online \u0111\u1ec1u th\u1ea5y b\u1ea1n chat.", "B\u1ea1n s\u1ebd b\u1ecb kh\u00f3a t\u00e0i kho\u1ea3n n\u1ebfu ch\u1eedi b\u1eady, qu\u1ea3ng c\u00e1o wap web tr\u00ean k\u00eanh th\u1ebf gi\u1edbi."};
            gL = new String[]{"Gia t\u1ed9c", "B\u1ea1n c\u00f3 th\u1ec3 chat v\u1edbi ng\u01b0\u1eddi trong gia t\u1ed9c t\u1ea1i \u0111\u00e2y"};
            gM = "Ch\u1eb7n k\u00eanh th\u1ebf gi\u1edbi: ";
            gN = "Ch\u1eb7n chat ri\u00eang: ";
            gO = "B\u1ed5 nhi\u1ec7m";
            gP = "B\u00e3i nhi\u1ec7m";
            gQ = "Tr\u1ee5c xu\u1ea5t";
            gR = "M\u1eadt kh\u1ea9u ph\u1ea3i c\u00f3 \u0111\u1ed9 d\u00e0i l\u00e0 6 k\u00fd t\u1ef1.";
            gS = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 ch\u1ec9 cho nh\u1eadp s\u1ed1.";
            gT = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 kh\u00f4ng \u0111\u01b0\u1ee3c ch\u1ee9a s\u1ed1 0 \u1edf \u0111\u1ea7u.";
            gU = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 ch\u01b0a \u0111\u00fang.";
            gV = "\u0110\u1ec3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng n\u00e0y b\u1ea1n ph\u1ea3i c\u00f3 V\u1ea1n bi\u1ebfn l\u1ec7nh.";
            gW = "K\u00edch ho\u1ea1t ch\u1ee9c n\u0103ng n\u00e0y ph\u1ea3i t\u1ed1n 10.000 y\u00ean. B\u1ea1n c\u00f3 mu\u1ed1n k\u00edch ho\u1ea1t kh\u00f4ng ?";
            gX = "Nh\u1eadp m\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7";
            gY = "Nh\u1eadp s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd";
            gZ = "B\u1ea1n ch\u01b0a nh\u1eadp s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd.";
            ha = "\u0110\u1ec3 l\u1ea5y m\u1eadt kh\u1ea9u cho '#'. B\u1ea1n ph\u1ea3i s\u1eed d\u1ee5ng s\u1ed1 \u0111i\u1ec7n tho\u1ea1i \u0111\u0103ng k\u00fd cho t\u00e0i kho\u1ea3n n\u00e0y.";
            hb = "\u0110\u1ed5i m\u1eadt kh\u1ea9u";
            hc = "Hu\u1ef7 b\u1ea3o v\u1ec7";
            hd = "M\u1eadt kh\u1ea9u c\u0169";
            he = "M\u1eadt kh\u1ea9u m\u1edbi";
            hf = "B\u1ea1n h\u1ecdc \u0111\u01b0\u1ee3c ";
            hg = "Nh\u1eadp th\u00f4ng b\u00e1o";
            hh = "Nh\u1eadp s\u1ed1 xu c\u1ea7n r\u00fat";
            hi = "Nh\u1eadp s\u1ed1 xu \u0111\u00f3ng g\u00f3p cho gia t\u1ed9c";
            hj = "Nh\u1eadp th\u00f4ng tin lo\u1ea1i th\u1ebb v\u00e0 m\u1ec7nh gi\u00e1";
            hk = "Nh\u1eadp th\u00f4ng tin s\u1ed1 seri v\u00e0 kho\u1ea3ng th\u1eddi gian n\u1ea1p";
            hl = "Nh\u1eadp s\u1ed1 l\u01b0\u1ee3ng t\u00e1ch";
            hm = "M\u1ec7nh gi\u00e1";
            hn = "Lo\u1ea1i th\u1ebb";
            ho = "S\u1ed1 seri";
            hp = "Th\u1eddi gian n\u1ea1p";
            hq = "Ch\u1eb7n tin nh\u1eafn";
            hr = "B\u00e1o l\u1ed7i v\u1edbi Admin";
            hs = new String[]{"G\u00e1n ph\u00edm t\u1eaft", "G\u00e1n v\u00e0o 5 \u00f4 \u0111\u00e1nh"};
            ht = "G\u1eedi tin nh\u1eafn th\u00e0nh c\u00f4ng";
            hu = "Ch\u00fac m\u1eebng b\u1ea1n \u0111\u00e3 g\u1edfi tin nh\u1eafn d\u1ef1 \u0111o\u00e1n th\u00e0nh c\u00f4ng.";
            hv = "Kh\u00f4ng th\u1ec3 g\u1eedi tin nh\u1eafn";
            hw = "Tin nh\u1eafn g\u1eedi kh\u00f4ng th\u00e0nh c\u00f4ng.";
            hx = "Kh\u00f4ng \u0111\u1ee7 xu \u0111\u1ec3 \u0111\u00f3ng g\u00f3p";
            hy = "S\u1ed1 l\u01b0\u1ee3ng t\u00e1ch kh\u00f4ng h\u1ee3p l\u1ec7.";
            hz = "Gi\u00e1 tr\u1ecb nh\u1eadp kh\u00f4ng h\u1ee3p l\u1ec7.";
            hA = "B\u1ea1n c\u00f3 mu\u1ed1n h\u1ee7y ch\u1ee9c n\u0103ng b\u1ea3o v\u1ec7 t\u00e0i kho\u1ea3n kh\u00f4ng ?";
            fx = "mu\u1ed1n th\u00e1ch \u0111\u1ea5u v\u1edbi b\u1ea1n \u1edf l\u00f4i \u0111\u00e0i. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            hB = "S\u1eafp x\u1ebfp theo gi\u00e1";
            hC = "S\u1eafp x\u1ebfp theo c\u1ea5p";
            hD = "S\u1eafp x\u1ebfp theo t\u00ean";
            hE = "V\u1eadt ph\u1ea9m \u0111\u00e3 \u0111\u01b0\u1ee3c g\u1edfi b\u00e1n v\u00e0o gian h\u00e0ng";
            hF = "M\u1ee9c ph\u00ed cho m\u1ed7i l\u1ea7n b\u00e1n l\u00e0 5.000 xu";
            hH = "B\u1ea1n c\u00f3 mu\u1ed1n b\u00e1n v\u1eadt ph\u1ea9m v\u1edbi gi\u00e1 # xu kh\u00f4ng ?";
            hI = "B\u1ea1n c\u00f3 mu\u1ed1n mua v\u1eadt ph\u1ea9m v\u1edbi gi\u00e1 # xu kh\u00f4ng ?";
            hJ = "Ng\u01b0\u1eddi b\u00e1n";
            hK = "c\u00f2n";
            hL = "g\u1ea7n";
            hM = "h\u1ebft gi\u1edd";
            hN = new String[]{"\u0110\u00e1", "N\u00f3n", "V\u0169 kh\u00ed", "\u00c1o", "D\u00e2y chuy\u1ec1n", "G\u0103ng tay", "Nh\u1eabn", "Qu\u1ea7n", "Ng\u1ecdc b\u1ed9i", "Gi\u00e0y", "B\u00f9a", "Linh tinh"};
            hG = " V\u1eadt ph\u1ea9m b\u00e1n \u0111\u01b0\u1ee3c ch\u1ecbu thu\u1ebf l\u00e0 5%";
            da = "Kinh nghi\u1ec7m";
            hO = "Th\u00f4ng b\u00e1o Server";
            hP = "Gi\u1edbi thi\u1ec7u b\u1ea1n b\u00e8";
            hQ = "L\u1eadt h\u00ecnh";
            hR = "S\u1ed1 l\u01b0\u1ee3t l\u1eadt c\u00f2n l\u1ea1i c\u1ee7a b\u1ea1n l\u00e0: ";
            hS = "mu\u1ed1n th\u00e1ch \u0111\u1ea5u v\u1edbi b\u1ea1n v\u00e0 c\u1ea3 gia t\u1ed9c. B\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng?";
            hT = "Max options";
            hU = "M\u1eddi ng\u01b0\u1eddi n\u00e0y";
            hV = "M\u1eddi t\u1ea5t c\u1ea3";
            hW = "'#' m\u1eddi b\u1ea1n v\u00e0o gia t\u1ed9c chi\u1ebfn. B\u1ea1n c\u00f3 mu\u1ed1n v\u00e0o kh\u00f4ng?";
            hX = "Nh\u1eadp t\u00ean th\u00e0nh vi\u00ean";
            hY = new String[][]{{"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 5.", "Ph\u00ed khai m\u1edf: 1.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 10.", "Ph\u00ed khai m\u1edf: 5.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 15.", "Ph\u00ed khai m\u1edf: 10.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 20.", "Ph\u00ed khai m\u1edf: 20.000.000 xu gia t\u1ed9c."}, {"Y\u00eau c\u1ea7u: gia t\u1ed9c \u0111\u1ea1t c\u1ea5p 25.", "Ph\u00ed khai m\u1edf: 30.000.000 xu gia t\u1ed9c."}};
            hZ = new String[]{"D\u00f9ng HP khi c\u00f2n d\u01b0\u1edbi: ", "D\u00f9ng MP khi c\u00f2n d\u01b0\u1edbi:", "D\u00f9ng th\u1ee9c \u0103n c\u1ea5p: ", "D\u00f9ng chi\u00eau h\u1ed5 tr\u1ee3", "Nh\u1eb7t y\u00ean", "Nh\u1eb7t Y\u00ean v\u00e0 HP,MP", "Nh\u1eb7t Y\u00ean, HP, MP v\u00e0 N.Li\u1ec7u", "Kh\u00f4ng nh\u1eb7t g\u00ec c\u1ea3"};
            ia = "D\u00f9ng ph\u00edm < v\u00e0 > \u0111\u1ec3 \u0111\u1ed5i gi\u00e1 tr\u1ecb";
            ib = "Ch\u1ea1m v\u00e0o \u00f4 th\u00f4ng s\u1ed1 \u0111\u1ec3 \u0111\u1ed5i gi\u00e1 tr\u1ecb";
            ic = "Kho\u1ea3ng c\u00e1ch qu\u00e1 xa, kh\u00f4ng th\u1ec3 ph\u1ee5c h\u1ed3i cho ng\u01b0\u1eddi kh\u00e1c \u0111\u01b0\u1ee3c";
            id = "     Nh\u1eadp gi\u00e1 tr\u1ecb ph\u1ea7n tr\u0103m th\u1ea5p t\u1ed1i thi\u1ec3u            (T\u1eeb 10 \u0111\u1ebfn 90)";
            ie = new String[]{"C\u1ea5p 1", "C\u1ea5p 10", "C\u1ea5p 20", "C\u1ea5p 30", "C\u1ea5p 40", "C\u1ea5p 50", "C\u1ea5p 60", "C\u1ea5p 70"};
            if = "T\u00e0i kho\u1ea3n \u0111ang \u0111\u01b0\u1ee3c b\u1ea3o v\u1ec7, vui l\u00f2ng m\u1edf kh\u00f3a.";
            ig = "Sinh l\u1ef1c";
            ih = "T\u00ean th\u00fa c\u01b0\u1ee1i";
            ii = new String[]{"Luy\u1ec7n th\u1ea1ch c\u1ea5p cao h\u01a1n b\u1eb1ng c\u00e1ch", "d\u00f9ng 9 th\u1ea1ch c\u00f9ng lo\u1ea1i ho\u1eb7c 3 th\u1ea1ch s\u01a1", "v\u00e0 \u0111\u00e1 11 ho\u1eb7c 3 th\u1ea1ch trung v\u00e0 \u0111\u00e1 12."};
            ij = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn T\u1eed tinh th\u1ea1ch s\u01a1 v\u00e0 trung c\u1ea5p";
            ik = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0110\u00e1 v\u00e0 T\u1eed tinh th\u1ea1ch \u0111\u1ec3 luy\u1ec7n";
            il = "Ch\u1ec9 c\u1ea7n d\u00f9ng 1 vi\u00ean \u0111\u00e1 \u0111\u1ec3 luy\u1ec7n";
            im = "C\u1ea7n k\u1ebft h\u1ee3p 3 T\u1eed tinh th\u1ea1ch (trung) v\u00e0 \u0111\u00e1 12 ho\u1eb7c 3 t\u1eed tinh th\u1ea1ch (s\u01a1) \u0111\u00e1 11";
            in = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn \u0111\u00e1 c\u1ea5p 11 tr\u1edf l\u00ean";
            io = "Ch\u1ec9 \u0111\u01b0\u1ee3c ch\u1ecdn T\u1eed thi\u00ean th\u1ea1ch c\u00f9ng lo\u1ea1i";
            ip = "Ph\u1ea3i c\u00f3 t\u1eeb 3 T\u1eed tinh th\u1ea1ch tr\u1edf l\u00ean m\u1edbi c\u00f3 th\u1ec3 luy\u1ec7n \u0111\u01b0\u1ee3c";
            iq = "S\u1ed1 l\u01b0\u1ee3ng T\u1eed tinh th\u1ea1ch qu\u00e1 nhi\u1ec1u";
            ir = "V\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng th\u1ec3 tinh luy\u1ec7n";
            is = "C\u1ea7n ph\u1ea3i c\u00f3 \u0111\u1ee7 20 chuy\u1ec3n tinh th\u1ea1ch \u0111\u1ec3 d\u1ecbch chuy\u1ec3n trang bi";
            it = "V\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng d\u00f9ng trong d\u1ecbch chuy\u1ec3n";
            iu = "C\u1ea5t k\u1eb9o";
            iv = "\u0110\u1ed9 tinh luy\u1ec7n";
            iw = "\u0110\u1ed9ng c\u01a1";
            ix = "Nhi\u00ean li\u1ec7u";
            iy = "Cho k\u1eb9o";
            iz = new String[]{"t\u1eed tinh", "t\u1eed tinh th\u1ea1ch s\u01a1", "t\u1eed tinh th\u1ea1ch trung", "t\u1eed tinh th\u1ea1ch cao"};
            iA = "V\u1eadt ph\u1ea9m \u0111\u00e3 tinh luy\u1ec7n \u0111\u1ebfn m\u1ee9c t\u1ed1i \u0111a";
            return;
        }
        GameMidlet.i = true;
        iI = "Equipment 1";
        iJ = "Equipment 2";
        iK = "Update Server";
        c = "This gem can't roasting.";
        b = "This gem reached max level.";
        d = "Register account to keep your character safe. Do you want to register?";
        e = "Hidden quest";
        f = "- Get 1 aggressive point.";
        g = "- Complete the cave of near school yard 1 times.";
        h = "- Complete hunting wild beast 1 times.";
        i = "- Upgrade equipment successful 1 times.";
        j = "- Complete daily quest 10 times.";
        k = "- Get 1000 battlefield points.";
        l = "- Complete seven beasts gate 1 times.";
        m = "- Enjoy lucky card 3 times.";
        iH = "Playing more than 180 minutes a day will adversely affect health.";
        p = "Win rate";
        q = "Your coin: ";
        r = "Players: ";
        s = "Lucky draw";
        t = "Join now";
        iG = "Continue";
        iB = "Your account has not been verified. If you delete the game, change the area, or log another account, your character will lose playing forever.";
        iC = "New Play";
        iD = "Play";
        iE = "Change Username";
        iF = "Server: ";
        u = "rank";
        v = "Challenge";
        w = "Info";
        x = new String[]{"Press change focus button to show all players on map", "For keyboard phones, assign shortcut keys 7,8,9 (or Q,W,E) to use skills.", "Berserk mode adds +2 agressive points.  Kill adds +1 agressive", "Sword, Kunai,and Blade increases Strength, Constitution, Dexterity", "Bow, Shuriken and Fan increases Chakra, Constitution, Dexterity", "Training as a team will earn experience and complete tasks faster", "Fighing other players on the battlefield will decrease combative points.", "When separated from the stone equipped, you will collect half amount of stone at the beginning.", "If you have enough action points, you can exchange coins from kin.", "The highest daily achievement in the arena will earn a reward.", "Find Rikudou to get into the arena.", "Precautionary measures cost money but will Increase the success rate of upgrading items", "When you reach Level 20, find Okanechan to received 10 gold bars.", "Gold bars will be split to 3 characters in 1 account"};
        y = "Please wait";
        z = "Wait";
        A = "Menu";
        String[] stringArray = new String[]{"30 Gold bars", "70 Gold bars", "180 Gold bars", "380 Gold bars", "1000 Gold bars"};
        B = "Need";
        C = "Move to";
        D = "Area";
        E = "Clear cache";
        F = new String[]{"Vi\u1ec7t Nam", "Global"};
        String[] stringArray10 = new String[]{"\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a", "\u1797\u17b6\u179f\u17b6\u17a2\u1784\u17cb\u1782\u17d2\u179b\u17c1\u179f"};
        G = "Exit game to change the area?";
        H = "Close";
        I = "Hide";
        J = "Auto";
        K = "Stand";
        L = "by";
        M = "Lock";
        N = "Unlock";
        O = "Seri number";
        P = "Card code";
        Q = "On";
        R = "Off";
        S = "Open link";
        T = "Charge";
        U = "Active";
        V = "Config";
        W = "Delete";
        X = "View";
        Y = "Continue";
        Z = "Inventory code";
        aa = "Scratch card";
        ab = "Next";
        ac = "Use";
        ad = "Sort";
        ae = "Throw it away";
        af = "Split";
        ag = "Equipment has been split, you get ";
        ah = "Yes";
        ai = "Get out";
        aj = "Get out";
        ak = "Withdraw coins";
        al = "Store coins";
        am = "Transfer coins";
        an = "Store";
        ao = "Sell";
        ap = "Sell more";
        aq = "Sell all";
        ar = "Price";
        as = "Buy";
        at = "Buy more";
        au = "No";
        av = "Exit";
        aw = "Chat";
        ax = "OK";
        ay = "Account";
        az = "Password";
        aA = "Re-input";
        aB = "Account";
        aC = "Pass";
        aD = "re";
        aE = "Please restart game";
        aF = "Re-input password";
        aG = "Remember";
        aH = "Uncheck";
        aI = "Register";
        aJ = "Forget password";
        aK = "High Graphic";
        aL = "Low Graphic";
        aM = "Please input account name";
        aN = "Account does not allow special characters.";
        aO = "You haven't added a password.";
        aP = "Your passwords do not match.";
        aQ = "Account name must have at least five characters";
        aR = "Wrong password.";
        aS = new String[]{"To register with name", "you have to follow the game rule."};
        aT = "What operator are you using? (You can recheck it in Menu)";
        aU = "Are you using your phone number to create account ?";
        aV = "private message";
        aW = new String[]{"message clan, group", "clan messages", "group message"};
        aX = "escort";
        aY = "Plus";
        aZ = "Plus more";
        ba = "potential point";
        bb = "skill point";
        bc = "Accept";
        bd = "Cancel";
        be = "List";
        bf = "Time";
        bg = "Achievement";
        bh = "Max";
        bi = "Accumulate";
        bj = "Connecting";
        bk = "Registering";
        bl = "Not finished";
        bm = "Time to finish";
        bn = "Teamwork";
        bo = "Select";
        bp = "Uncheck";
        bq = "Select items to view the information.";
        br = "Assign";
        bs = "Result";
        bt = "Review";
        bu = "Level";
        bv = "Level";
        bw = "Do you want to exit?";
        bx = "Please rename your character";
        by = "This server is maintained or overloaded. Please try again later or choose another server.";
        bz = "Create";
        bA = "Name";
        bB = "Name of character you want to friend";
        bC = "Friend link successful.";
        bD = "Loading... ";
        bE = "Close";
        bF = "Get reward";
        bG = "lucky gift";
        bH = "Inventory was expanded";
        bI = "Distance too far for escort, quest failed";
        bJ = "The escort was wounded, quest failed";
        bK = "forever";
        bL = "Not upgrade";
        bM = "Can not upgrade.";
        bN = "Use special items to upgrade";
        bO = "Train";
        bP = "Stone train successful, you get";
        bQ = new String[]{"Just transfer same type equipment", " or higher.", "Will lock fitted after transformation.."};
        bR = "failure, you get";
        bS = "Message sent, please wait for confirmation.";
        bT = "Can not send message. Please check you balance or restart the game.";
        bU = "Sending Coins";
        bV = "Start";
        bW = "Choose at least 2 stones or more";
        bX = "Choose the equipment that you want to split the Stone";
        bY = "Choose item and coins to exchange";
        bZ = "Move to luggage to choose";
        ca = "Change";
        cb = "Cell";
        cc = "Cells";
        cd = new String[]{"Key Q", "Key W", "Key E"};
        ce = new String[]{"Key 7", "Key 8", "Key 9"};
        cf = new String[][]{{"tomboy", "with brooch", "pony tail", "curly"}, {"head band", "afro", "samurai", "spike"}};
        cg = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment", "Mounts", "Bijuu"};
        ch = new String[]{"Costume shop", "Inventory"};
        ci = new String[]{"Cap", "Inventory"};
        cj = new String[]{"Cloth", "Inventory"};
        ck = new String[]{"Gloves", "Inventory"};
        cl = new String[]{"Pants", "Inventory"};
        cm = new String[]{"Shoes", "Inventory"};
        cn = new String[]{"Necklace", "Inventory"};
        co = new String[]{"Ring", "Inventory"};
        cp = new String[]{"Gems", "Inventory"};
        cq = new String[]{"Charms", "Inventory"};
        cr = new String[]{"Weapons", "Inventory"};
        cs = new String[]{"Medicine", "Inventory"};
        ct = new String[]{"Medicine", "Inventory"};
        cu = new String[]{"Food", "Inventory"};
        cv = new String[]{"Food", "Inventory"};
        cw = new String[]{"Upgrade", "Inventory"};
        cx = new String[]{"Stand", "Inventory"};
        cy = new String[]{"Transfer", "Inventory"};
        cz = new String[]{"Training Stone", "Inventory"};
        cA = new String[]{"Inventory", "Inventory"};
        cB = new String[]{"Shop", "Book Store", "Fashion Store", "Clan Store"};
        (new String[1])[0] = "Clan shop";
        cD = new String[]{"Split Stone", "Inventory"};
        cE = new String[]{"Trade", "Inventory"};
        cF = new String[]{"Upgrade essence", "Inventory"};
        cG = new String[]{"Add attributes", "Inventory"};
        cH = new String[]{"Enhance equipment", "Inventory"};
        cI = new String[]{"Socketing", "Inventory"};
        cJ = new String[]{"Leveling gem", "Inventory"};
        cM = new String[]{"Gem Roasting", "Inventory"};
        cN = new String[]{"Extract gem", "Inventory"};
        cL = new String[]{"Completed quest", "Inventory"};
        n = "I will help decrease bad options of this gem.";
        o = "I will help you extract gem from this item.";
        cO = new String[]{"- Use kin incase not enough coin", "- Move to inventory to choose stone", "- Amount of stones from 2 to 24"};
        cP = new String[]{"- Use coin incase not enough kin", "- Upgrading need Gold bar", "- Choose Equiptment and stone only", "Your equipment has reached max level"};
        String[] stringArray11 = new String[]{"- Move to inventory to choose Equipment", " After separation will be back to begining form", "Separation successfull"};
        cQ = new String[]{"- Use coin incase not enough kin", "- Choose Equiptment and Gem"};
        cR = "Lock Transfer";
        cS = "- Train Stone to level";
        cT = "- Need: # kin";
        cU = "- Need: # Gold bars";
        cV = "- Need: # coins";
        cW = "- Percentage of success.";
        cX = "(success ";
        cY = "Do you want to remove this item?";
        cZ = "Add";
        db = "Locked";
        dc = "Killed";
        dd = "Arrest Beast";
        de = "Kill Elitez";
        df = "Kill Chief";
        dg = "Protect the child";
        dh = "No lock";
        di = "Expires";
        dj = "Price: # kin";
        dk = "Price: # coins";
        dl = "Price: # clan coins";
        dm = "Price: # kin";
        dn = "Price: # gold bars";
        do = "Gold bar";
        dp = "Do not have";
        dq = "Next level: level #";
        dr = "Current level: level #";
        ds = "Maximum level";
        dt = "Reached maximum level";
        du = "Require: level";
        dv = "Class: ";
        dw = new String[]{"Main quest", "Sub quest"};
        dx = "Quest";
        dy = "Obtain quest at";
        dz = "White Side";
        dA = "Black Side";
        dB = "Yellow Side";
        dC = "Neutral";
        dD = "team";
        dE = "Find team";
        dF = "Your current aggressive points are ";
        dG = new String[]{"Friends", "Hostile"};
        dH = "You are not friends with anyone";
        dI = "waiting confirmation";
        dJ = "added you to friends list";
        dK = "You have added";
        dL = "to the list";
        dM = "You and";
        dN = new String[]{"store", "Myself", "Map", "General", "Exit", "Jewellery", "Feature", "Pharmaceutical Key", "Pharmacy", "Grocery Key", "Grocery", "Strengthen", "Training", "Training key", "Inventory", "Split Equipment", "Area", "Trade", "Message"};
        dO = new String[]{"Passive Support", "Active use", "Active use", "Active use", "Active use"};
        String[] stringArray12 = new String[]{"You are run out off skill points. Upgrade your level for more skill points.", "You are run out off potential points. Upgrade your level for more potential points. "};
        dP = new String[]{"Character: ", "Agressive: ", "Level: ", "Class: ", "", "HP:", "MP: ", "Speed: ", "Attack: ", "Anti Fire: ", "Anti Ice: ", "Anti Wind: ", "Reduce Pain: ", "Accurate point:", "Dodge ability: ", "Critical: ", "Close combat strike back: ", "Anti chakra: ", "Anti chakra back: ", "Action points: "};
        dQ = " times";
        dR = new String[]{"Genin", "Chunin", "Jounin", "Kage"};
        dS = new String[]{"Action point: ", "Weapon Fame: ", "Necklace Fame: ", "Ring Fame: ", "Gems Fame: ", "Charm Fame: ", "Hat Fame: ", "Cloth Fame: ", "Gloves Fame: ", "Pants Fame: ", "Shoes Fame: ", "Accomplish daily quest: ", "Arrest Beast: ", "Read the basic potential book: ", "Read the basic skill book: ", "Clan: ", "Cave time left: ", "Star Fame: ", "Wind Thunder Mooncake: ", "Ice Fire Mooncake: "};
        dT = new String[]{"Name: ", "Gender: ", "Hair: "};
        dU = new String[]{"Female", "Male"};
        dV = new String[]{"Strength", "Dexterity", "Constitution", "Chakra"};
        String[] stringArray13 = new String[]{"Strength", "Agility", "Health", "Chakra"};
        dW = "You were not killed by anyone.";
        dX = "You won #.";
        dY = "You lost #.";
        dZ = "Your fight match between you and # is over.";
        ea = new String[]{"", "Elitez", "Chief", "Beast"};
        eb = " try to kill you";
        ec = "Potential point";
        ed = "Skill point";
        ee = "Not enough MP to use";
        ef = "Only select unlocked items";
        eg = "Only select unlocked items that haven't expired";
        eh = "Just choose Stones to train";
        ei = "Just choose Stone, Equipment and upgrade insurance.";
        ej = "Just choose Equipment and conversion items.";
        ek = "Can not upgrade";
        el = "Maximum upgrade";
        em = "Only upgraded item or equipment to split.";
        en = "Items for Trading are full.";
        eo = "Amount is Full.";
        ep = "Not enough points.";
        eq = "Please input added points.";
        er = "You need to input card information.";
        es = "You need to input card value information.";
        et = "You need to enter serial number.";
        eu = "You need to enter topup times.";
        ev = "You need to enter a name";
        ew = "Enter Points";
        ex = "Enter Coins";
        ey = "Enter quantity";
        ez = "Username";
        eA = "Coin";
        eB = "Kin";
        eC = "Gold bar";
        eD = "Put in inventory";
        eE = "Do you really want to dismissed this one?";
        eF = "Expulsion of members will reduce Clan budgets (see details in Kanata NPC). Do you want to dismiss them?";
        eG = "Leaving clan will reduce your coins (see Kanata for details.)  Are you sure you want to leave?";
        eH = "After using this item, it will be locked. Do you want to use it?";
        eI = "Sold items can not be recovered. Do you want to sell this item?";
        eJ = new String[][]{{"cap"}, {"wea", "pon"}, {"cloth"}, {"neck", "lace"}, {"glo", "ves"}, {"ring"}, {"pants"}, {"gems"}, {"shoes"}, {"charm"}, {"pet"}, {"mask"}, {"ninja", "yoroi"}, {"clan", "item"}, {"Emp", "ty"}, {"Ancient", "Book"}, {"Ar", "mor"}, {"Sad", "dle"}, {"Tas", "sels"}, {"Coro", "net"}, {"Eng", "ine"}, {"Sat", "nav"}, {"ECU", ""}, {"N20", ""}, {"m\u00f3ng", "vu\u1ed1t"}, {"d\u00e2y", "chuy\u1ec1n"}, {"th\u00fa", "b\u1ea3o"}, {"x\u00edch", ""}};
        eK = new String[]{"Not a student", "School: Hirosaki", "School: Ookaza", "School: Haruna"};
        eL = new String[]{"", "Attribute: Fire", "Attribute: Water", "Attribute: Wind", "", "", ""};
        eM = "You got";
        eN = "You have not entered the amount of gold bars.";
        eO = "You don't have enough coins to move.";
        eP = "You don't have enough coins to store.";
        eQ = "You don't have enough coins to withdraw.";
        eR = "You don't have enough gold bars to sell.";
        String[] stringArray14 = new String[]{"Success stone train", "Training has failed"};
        eS = new String[]{"Success,  equipped with level up ", "failed, return level of equipment", "equipment upgraded maximum", "equipment level"};
        eT = new String[]{"Success socketing", "Socketing has failed"};
        eU = "month";
        eV = "week";
        eW = "day";
        eX = "hour";
        eY = "second";
        eZ = ",minute";
        fa = "Number of target";
        fb = "Range";
        fc = "MP cost";
        fd = "Cool down time";
        fe = "You need at least two stones to train.";
        ff = "Gender does not match";
        fg = "Don't have any one else";
        fh = "Your level is too low";
        fi = "Stone has reached the maximum level";
        fj = "Your stones after leveling will be blocked. Would you like to continue?";
        fk = "You don't have enough coins to level stone";
        fl = "You don't have enough gold bars to upgrade equipment";
        fm = "You don't have enough coins to upgrade equipment";
        fn = "Many training stones will be wasted. Are you sure you want to upgrade";
        fo = "After upgrade this item will be locked. Do you want to continue?";
        fp = "Can not split the unupgraded item.";
        fq = "Your luggage doesn't have enough space.";
        fr = "Do you really want to split this item?";
        fs = "Do you really want to convert?";
        ft = "Welcome to trading. Do you want to trade?";
        fu = "Welcome to the clan. Do you want to join Clan '#' ?";
        fv = "Do you want to join this clan?";
        fw = "wants to fight with you. Do you accept?";
        fy = "invite you to Party. Do you want to join?";
        fz = "ask you to join their Party. Do you accept?";
        fA = "Convert successful.";
        fB = new String[]{"Gender: Female", "Gender: Male"};
        fC = "Area";
        fD = "Population";
        fE = "Party";
        fF = "At this moment, you have not joined any Party.";
        fG = "times";
        fH = new String[]{"Info", "Member", "Warehouse", "Statistic", "Guardian"};
        fI = new String[]{"Clan: ", "Clanmaster: ", "Member: ", "Level: ", "Experience: ", "Budget: ", "Establish: ", "Donation: ", "Maintenance fee: ", "Upgrade fee: ", "Enter the Territory of Clan: remain ", "Week donation: ", "Use Clan card mark: remain "};
        fJ = new String[]{"Coins at", "Establish clan, budget has", "expulsion, budget decrease", "clan contribution, budget increase", "withdraw clan budget, budget decrease", "Fee for maintain clan, budget decrease", "upgrade clan, budget decrease"};
        fK = "You are not a member of any clan";
        fL = "Send to Clan Member";
        fM = new String[][]{{"Hirosaki School"}, {"Haruna School"}, {"Ookaza School"}, {"Village", "Kojin village", "Sanzu village", "Tone village", "Fish Village", "Chakumi Village", "Echigo Village", "Oshin Village"}, {"Area"}};
        fN = new String[]{"Cap", "Ring", "Cloth", "Necklace", "Gloves", "Ring", "Pants", "Gems", "Shoes", "Charm"};
        fO = new String[]{"Active hidden", "Active level"};
        fP = new String[]{"", "Fire", "Water", "Wind"};
        fQ = new String[]{"Character", "Level", "Jewellery"};
        String[] stringArray15 = new String[]{"You do not have an account", "choose menu to register."};
        fR = "You do not have any special skills.";
        fS = "You do not have any special weapons. Go to Menu/Status/Equipment to check";
        fT = "This item was locked.";
        fU = "Items, accessories and stones";
        fV = "price (coin)";
        fW = "price (kin)";
        fX = "You are hungry, eat some more";
        fY = "You level is too low to use this item";
        fZ = "Out off MP";
        ga = "Out off HP";
        gb = new String[]{"Trade", "Fight", "Berserker", "Add friend", "Invite to Party", "Recover", "Check info", "Private chat", "Invite to clan", "Request to join clan", "Block request to joint clan", "Auto recover", "C\u1ea5m Chat"};
        gc = "You are in ";
        gd = new String[]{"Let's find", " at ", " to get the quest.", "You have finished all quests this version, please wait for the next version."};
        ge = new String[]{"Exhausted", "Starring", "Come back", "Revive now (1 Gold bar)"};
        gf = "After joining a class, you can receive any quest from the principal.";
        gg = "Create team";
        gh = "Leave team";
        gi = "Teamleader";
        gj = "Lock team";
        gk = "Unlock team";
        gl = "Ask to join party.";
        gm = "Refresh";
        gn = "You are not a member of any team.";
        go = "Empty information.";
        gp = "Cannot find any Party now.";
        gq = new String[]{"PK normal", "PK team", "PK clan", "PK Berserker"};
        gr = new String[]{"PK status", "Friend", "Enemy", "Party", "Find party", "Clan", "Protect account", "Auto"};
        gs = new String[]{"Map", "Quest", "Clan"};
        gt = new String[]{"Clan Master", "Chief Elder", "Elder", "Elite", "Member"};
        gu = new String[]{"(CM)", "(CE)", "(ED)", "(EL)"};
        gv = new String[]{"Online only", "Left", "Notice", "Contribute", "Withdraw funds", "Upgrade", "Invite to territory", "Invite to clan war", "Unlock"};
        gw = "Sort by dedicating week";
        gx = new String[]{"Expulsion", "Transfer", "Make friend"};
        String[] stringArray16 = new String[]{"Chief of Elders", "Elders"};
        gy = " You are promoted to team leader.";
        gz = "You were kicked off of team.";
        gA = "Invite to team";
        gB = "Add";
        gC = "Inappropriated Weapons.";
        gD = "Do you want to delete this person from your friend list?";
        gE = new String[]{"Go to school to upgrade your marks."};
        gF = new String[]{"Strength = Attack", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = MP"};
        gG = new String[]{"No need to upgrade strength", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = Attack, MP"};
        String[] stringArray17 = new String[]{"Strength = 10 attack", "Agility = 10 accurate", "Health = 10s summon time", "Chakra = 1 MP"};
        gH = "Close current tab.";
        gI = new String[]{"Public chat", "You can chat with people around you here."};
        gJ = new String[]{"Same party", "You can chat with your Party member here."};
        gK = new String[]{"Global chat", "You will lose 5 Gold Bars for each use.", "This message will broadcast to everybody.", "Your account will automatically be locked if you attempt to advestise any wap website, or use profanity."};
        gL = new String[]{"Clan", "Yon can chat with Clanmates in this place"};
        gM = "Block global chat: ";
        gN = "Block private chat: ";
        gO = "Appoint";
        gP = "Dismiss";
        gQ = "Expulsion";
        gR = "Maximum 6 digits.";
        gS = "Just allow number digit for protected password.";
        gT = "Protected password can not start with number 0.";
        gU = "Wrong password.";
        gV = "To use this function, you have to have Multi Teleport Card.";
        gW = "To activate this function, you have to pay 10.000 kin. Do you want to activate?";
        gX = "Password";
        gY = "input the mobile number that you want to register";
        gZ = "You did not input the number that you used to register this game before.";
        ha = "To get the password for account '#'. You must use the phone number used to register this account.";
        hb = "Change pass";
        hc = "Cancel protection";
        hd = "Old password";
        he = "New password";
        hf = "You have learned ";
        hg = "Input your message content";
        hh = "Input the amount of coin to withdraw";
        hi = "Input the coin amount to donate to the Clan.";
        hj = "Input type of card and value";
        hk = "Input serie number and time of charging.";
        hl = "Input amount of split time.";
        hm = "Value";
        hn = "Type of card";
        ho = "Seri number";
        hp = "Time of charging";
        hq = "Block message";
        hr = "Submit this bug to Admin.";
        hs = new String[]{"Assign key", "Assign to 5 key"};
        ht = "Send message success.";
        hu = "Congratulations! your choice is correct.";
        hv = "Can not send message.";
        hw = "Send failure.";
        hx = "Not enough coin to contribute";
        hy = "The amount to split is invalid.";
        hz = "invalid input value.";
        hA = "Do you want to cancel Protect account function?";
        fx = "wants to challenge you in the battle arena. Do you agree?";
        hB = "Sort by price";
        hC = "Sort by level";
        hD = "Sort by name";
        hE = "Item is sent for trading";
        hF = "Trading fee is 5.000 coin";
        hH = "Do you want to sell item with # coins ?";
        hI = "Do you want to buy item with # coins ?";
        hJ = "Seller";
        hK = "remain";
        hL = "a few";
        hM = "seconds";
        hN = new String[]{"Stone", "Cap", "Weapon", "Cloth", "Necklace", "Gloves", "Rings", "Cloths", "Gems", "Shoes", "Charms", "Miscellaneous"};
        hG = "pay 5% of value as tax";
        da = "Experience";
        hO = "Announcement";
        hP = "Invite friends";
        hQ = "Choose card";
        hR = "Flip remaining: ";
        hS = "Challenges you and your clan. Do you agree ?";
        hT = "Max options";
        hU = "Invite this person";
        hV = "Invite all";
        hW = "'#' invites you to join the clan war. Do you want to join?";
        hX = "Input member's name";
        hY = new String[][]{{"Requirement: Clan level 5", "Cost to Open: 1.000.000 clan coins."}, {"Requirement: Clan level 10.", "Cost to Open: 5.000.000 clan coins."}, {"Requirement: Clan level 15.", "Cost to Open: 10.000.000 clan coins."}, {"Requirement: Clan level 20.", "Cost to Open: 20.000.000 clan coins."}, {"Requirement: Clan level 25.", "Cost to Open: 30.000.000 clan coins."}};
        hZ = new String[]{"HP: ", "MP: ", "Using food level: ", "Always using skill to support", "Pick up Kins", "Pick up Kins and Hp, MP", "Pick up Kins, Hp, Mp and Material", "Not picked up"};
        ia = "Use button < and > to change value";
        ib = "Touch to change value";
        ic = "Distance is very far, Can not heal another people";
        id = "Percent value is from 10 to 90";
        ie = new String[]{"Level 1", "Level 10", "Level 20", "Level 30", "Level 40", "Level 50", "Level 60", "Level 70"};
        if = "Account required password, input password to unlock.";
        ig = "Vitality";
        ih = "Name of mounts";
        ii = new String[]{"Upgrade essence by using 9 essences", "of the same kind or 3 common essences", "and stone level 11 or 3 rare essences and stone level 12."};
        ij = "Only common essence and rare essence";
        ik = "Only stone and essence to upgrade essence";
        il = "Just only 1 stone to upgrade";
        im = "Need to use 3 rare essences and stone level 12 or 3 common essences and stone level 11";
        in = "Have to use stone level 11 and 12";
        io = "Have to use essences of the same kind";
        ip = "Have to has 3 essences to Upgrade";
        iq = "Essences are excessive";
        ir = "This equipment can not Enhance";
        is = "Not enough material";
        it = "This function is not available for this equipment";
        iu = "Save candy";
        iv = "Enhance level";
        iw = "Engine";
        ix = "Fuel";
        iy = "Give candy";
        iz = new String[]{"essence", "essence", "common essences", "rare essences"};
        iA = "Equipment enhanced to max level already";
    }

    public static String a(String string, String string2) {
        return at.a(string, "#", string2);
    }
}

